appSettings:
    AppSettings:
        AppBaseURL: ENC[AES256_GCM,data:OZUPTPSuBmdc6/yTw3N91xaWypqFLssR462bLNL0,iv:lLlHf83wUJoLfm0HaUiXWQ+zsF7TJA+9vRL4v/TtOXI=,tag:O3+N4ZOVJaBfrTxKgHBSuQ==,type:str]
        AllowedHosts: ENC[AES256_GCM,data:nw==,iv:kVPMq68BYdmcneL8HlcGsUAXj62eDAMDTXr5/f5P50c=,tag:lNH2rXdZIseu+u718TjSrA==,type:str]
        AllowedOrigins: ENC[AES256_GCM,data:Vt2kU8VCTOWrJFaF9hlMxs9eKPt5c1Qvcw/wUmm7k5cs2f9quQNNwXQ+HSKuuMXOovy/lO9hA8v3PPIItJM4ptkNo3G0pEKWOaQ=,iv:G23llMprf3CYZgKP4JDHJeefIGfnFd+/hkRYb5MU7zc=,tag:01tPOQdC8/8I7hCgEH8bBg==,type:str]
        SSIIssuerNameYomaOrganization: ENC[AES256_GCM,data:DYEm9aZShdADO4bbXHHyvmmPWsZKHoTLHXfMwid8Eg==,iv:PSn3GwQxhPa5JyCtdFscvYRONRdNROBwC5oJtYXrw7U=,tag:Wz/AlFnuB59OoBv/yQhqZA==,type:str]
        SSISchemaFullNameYoID: ENC[AES256_GCM,data:Yg3jjX/6neo9yh1u,iv:WEaBSfQlOU9tzEH6rFfzXENpasYFs0MCvDeFsV+tlc8=,tag:+9/9bkyQOOOOCE5QlxkIzw==,type:str]
        TestDataSeedingEnvironments: ENC[AES256_GCM,data:9EaHKW+OpmGJuMRi02ZX6BLE,iv:VBwZX+e4LCG7V0zfEVD4h0N4fNMp6XpEHbBYFTalZJ8=,tag:VxXKiLUOATkedaeybBHI0Q==,type:str]
        Hangfire:
            Username: ENC[AES256_GCM,data:H528r+I=,iv:vacoWzdRIGA/42kmEd/UtoagSO+PaRQgf2t5jGXOLvc=,tag:5byAy3IKDS+rpSnAe/nKIQ==,type:str]
            Password: ENC[AES256_GCM,data:cYY+bQhcY+ozjHKaaIadVP2e6Hyvs64XaL/e0PLaQw8=,iv:7zDZUtx/++sIHz6AIJNbSnR6SQl1R03p6/Moc5NWzNM=,tag:1w3SAzyfLB4VyH95JStpKA==,type:str]
        Sentry:
            Debug: ENC[AES256_GCM,data:24FML7k=,iv:SmLFlYN5GLlD7hHr3YCIBuWBs2sQTBs29WnX24mOGpw=,tag:S4VRn9oaXK1+zqY7Za/n8Q==,type:bool]
        Logging:
            LogLevel:
                Default: ENC[AES256_GCM,data:efVYnPzDl8X0PC0=,iv:XenfoAkvamZ08qu6mBEYC7W1qFvwa0KFmYl/x5ClDHU=,tag:7kQUBJDGDQ/OmLVuYSlkRw==,type:str]
                Microsoft: ENC[AES256_GCM,data:asK1iJRkww==,iv:XsBxV7vLjC4UbwkS7MG5IoCEI3PJdWdVrn/JVQTxa0c=,tag:fOREplxwuOk1Wdk92yzswg==,type:str]
                Microsoft.Hosting.Lifetime: ENC[AES256_GCM,data:C3dlZe70RnzOVc4=,iv:IGQFWPAHdIFsIIV04fuq3qTPZQ+oO0fTq2AFysE9GIU=,tag:NzxOp7p6sVap5wGBskF3TQ==,type:str]
    AWSS3:
        Buckets:
            Public:
                AccessKey: ENC[AES256_GCM,data:+20UwpCUrcpJ9dmtvmTDXyUj+yE=,iv:hVAqA/MC1zuIx0gi76K0JaPb/ep52kUek/wiP0WrkUU=,tag:ekBCYpfNoFWFNv8uBeeSlA==,type:str]
                SecretKey: ENC[AES256_GCM,data:hpmFzqIlGJ9DVkEnt8PLKE50jVMyeuKfIEpCiiMY9KBBsRYxqN1/4w==,iv:wTclqk8oOXPiL967SDTWCwDnHkZRDmRS4+hUiPWIqkM=,tag:ihSQYnlSZISyC/kC1AR50A==,type:str]
                BucketName: ENC[AES256_GCM,data:3JQGCbnXieRzeAME5qCOaPAtqEPgvQ==,iv:R+STmi8qKCIcvAWsABZzLu+dOL23ZlpSG0vtBfrYNkI=,tag:+aG/M5gCLJkWIl75m8tX3w==,type:str]
            Private:
                AccessKey: ENC[AES256_GCM,data:a6gFo1Hm6lEzr/5RFBxIL5HEEH0=,iv:dUP19Qi2egGrRMDERNtc/AHG0yhcrd2b/TF7YJ5cpoQ=,tag:8UBvnpucphIw3e+FXRDrVw==,type:str]
                SecretKey: ENC[AES256_GCM,data:aC8NRtfj7My+3DNJadibli9vLWiE/lZ+bIHaRBsQxgQKyDE4ICDM8Q==,iv:3MvEgqw3oXJTstbIkxOu4hEBbLdkF8PlCORN9Fw74AQ=,tag:mPcS0Flna/BX292dg+q3iA==,type:str]
                BucketName: ENC[AES256_GCM,data:i2T2kt5uCTF3kxLfVkpsYm7L07Ym2oQ=,iv:gzMlh5vz/ju2fbYlUxVlZE3zsz3/PHAJ8hovRnUWF5A=,tag:7DvI1RtZNpZ38AE2DKrN/w==,type:str]
    ConnectionStrings:
        SQLConnection: ENC[AES256_GCM,data:OUcAB/q82IjOqYRWjNWxAhl2OaW9/UbDZpHMq/vMIwhEikYFW1jn4DeKGG37unCS7c9jVqAvLLrnA5FuOSmLlEtmpZdkontEcG5wrqbkG6yN6N7QhQhxmk35Pzr2WbAlBl6sCRpxtfWkXgYWTSBUdOoV2GC8469UElLZJ4tLSARYWRvtObYn3/fzTg0G+8VmJZsdl+oJpik22BdrhHgowp2eLkIuzPBHeIQ6/caKu4TjikxAaDf1bEL2xMtjgNb3Rspa3Tb6j88qmCxRIRtCKnozwvRCCsdXgsowMK8kNYluwchPTnv51yzAHzowbVrQakcOeZn8ugazvP8axx3CgpdjQf8yg+3+ceyMhA==,iv:optPMiPP8KkKUvHLScP5FFIMgFiA+ReaEp+RDJ2JJXo=,tag:qHe0r4IktLnYgLCCyQ1y7Q==,type:str]
    KeycloakAdmin:
        Admin:
            Realm: ENC[AES256_GCM,data:I224QbXy,iv:Xy4z1mqN/csZNSUpUD02ogLKsrnUjRwMEHvLJauXsHY=,tag:0dvH2ZsUHSDrfttm8w3YcA==,type:str]
            Username: ENC[AES256_GCM,data:vJgwwg7HxWcgwP8=,iv:lxaCno04zjjWYU2xUCqhKAoorRhzNgRXfDyOoAkLqJw=,tag:Z8JTXjJugsKqnuHMAio+Wg==,type:str]
            Password: ENC[AES256_GCM,data:HQqzKQofeGfqU1RAixn1JXVbTasQDlL1J8WY/Ll5eKc=,iv:+wMvwMpHsrBu1jZIqJP7SSfGkyWlC8uOm6vhQgF5pvY=,tag:8Q/TVKItAU50ily0HICmNQ==,type:str]
        WebhookAdmin:
            Username: ENC[AES256_GCM,data:Z3W7Rp4JLw==,iv:y9+YwNilVodDCzV38R8CkYFbqjgoqag3/iv6oYRMMNM=,tag:/YXCmveK5B5qAQiQsiNjTg==,type:str]
            Password: ENC[AES256_GCM,data:YQ8FgGJB5MlF0Es2ZiuSBM5hoIgFMBOQp0koiT7OTAc=,iv:5szxrwCX9NgieF3QJJAHKUNKimrtuBuuj0bFgZ2h5UM=,tag:YuFqLuel5n5MI3LxCyOreg==,type:str]
    Keycloak:
        realm: ENC[AES256_GCM,data:PLvRqg==,iv:Fq3A9KN66zX1lRcPsSn45VIqVPmcu7J8br3VsToBRes=,tag:7c9SWoNktCRUabPDSScjeQ==,type:str]
        auth-server-url: ENC[AES256_GCM,data:KIh/cUTY02kc+9j24UN1wPbTbm5rjxdj1ZW2sNqzxEI=,iv:xsCwL6Iv0uV5ywuEj2Wyr7SLzEz7gliuVIbL/Zrebhs=,tag:3s5NHsu3G1iyRViH1YcQEg==,type:str]
        ssl-required: ENC[AES256_GCM,data:faD2tg==,iv:YRClzMADJDhtC0pGWj/7uTMCP8jeQpwDgLl2M+9ac8c=,tag:U/XrClh/99agjZXwFatOrg==,type:str]
        resource: ENC[AES256_GCM,data:Mykh2QFfzs0=,iv:liqyX7wP84t9YXTA5oR82FCvThfTzVEVDlXCAeixhfk=,tag:j+V+MfB02t0reRve6iZ3aQ==,type:str]
        verify-token-audience: ENC[AES256_GCM,data:Au64eg==,iv:bursGObVIbd8OQQp5yXYaCI0Hdks9Ii0zRJQSZEh1Nw=,tag:JPfL5csjyu762J05luNF+Q==,type:bool]
        credentials:
            secret: ENC[AES256_GCM,data:Y7dOtJdmHla2EyXI33idzQ2adG1wOp0MW4yy2y2MFoI=,iv:3wrCRz0ZDUMRTE5rju88NXg39Ze0F1+GvtA6y3OCrnI=,tag:l3QVdlRaaUinWX+TysvkeA==,type:str]
        use-resource-role-mappings: ENC[AES256_GCM,data:d4S6Sw==,iv:Vmus7DfE66MFYDWq8ocbV9xyp6hO5+xSMjike+j7kA8=,tag:mfXwf3TBudWyxhE4zjqSsQ==,type:bool]
        confidential-port: ENC[AES256_GCM,data:TA==,iv:/wmGZY64cZKUZJXAij6oewJ2XTHXR+9SxCLT9ZqlCvg=,tag:293DLuvrFkcrC/ndR14FfA==,type:int]
    Sentry:
        Dsn: ENC[AES256_GCM,data:v4rsPhTZjcdkSKnkxIcGRxeq9T/7Bi3NiXhUv3rlkhu/a8CtZwbxjxdHCcNtoIxNrZc3qhlFOEHRyEH6OBDWh0BoD06jkYa+Kncs5UQUNky47w==,iv:dWkS73DYu3oaG328QkQF5PxiG6r3ZpATC+gtLoDkMuE=,tag:XofWXb65Av7tosSNy2TCVA==,type:str]
    Emsi:
        ClientId: ENC[AES256_GCM,data:6rWVp9+8,iv:dJwVeHoDp5inCU/0bp1EQ8j1yaJeSGfruv/X0NSGKjQ=,tag:VWLbkgPZtXGGGk8IotocqQ==,type:str]
        ClientSecret: ENC[AES256_GCM,data:lbnzros9pZE=,iv:5FYHQLYbDopWWozbjKnRIIi5vWyua9omRk5qiouxkMk=,tag:veKOB9QYiMmMTLFA4hq+XA==,type:str]
    SendGrid:
        ApiKey: ENC[AES256_GCM,data:gcdhLye2sSBqfK+09xgDsTcLUnJGdw818K2IOvG4QF23D6thnn75uVxFlOVRjSgmjebC/1C+3YIhss+NguS4SQoQSw6k,iv:i1Q6tvDXv5oGyi9CcuWL3sASeykI7tPWYmm5uU2ZcNI=,tag:vMCVhNk+q+tIaNNfJTLOfw==,type:str]
    Zlto:
        Username: ENC[AES256_GCM,data:84aVrAZtu3fqLMIwAw==,iv:bEYCuOWpKvP3B+0G/j5e/FQPDQHILEtRFLNXdf+7AbQ=,tag:M8KMUE/O5VW/zG8JAXDsMQ==,type:str]
        Password: ENC[AES256_GCM,data:pRG8vMdwhN1o,iv:WmvuaxB439Quu0Oof1cCLWyTEBxtWwF4noaJmo8nblA=,tag:ewl40WOpgkhVzI2QqvJqKg==,type:str]
        ApiKey: ENC[AES256_GCM,data:uE9Q6Ler2J0WFEzBWxksc2FAltNBNyz1hFyw0vifeuMOtihd,iv:JfCc0fhWvEjy5EP4r6Pc+wJW6TD3MO8dlWfJcsyjyIA=,tag:6aXVjQ+vHkf1PF8FKLde2g==,type:str]
    AriesCloudAPI:
        DebugOutput: ENC[AES256_GCM,data:2E+sFps=,iv:KH4/zFPwFZ79cgC/j9kgGHXFbWIXfP9UzPnbB3qP6j4=,tag:SZ/71pnhN5NjAmiJ7A5cGQ==,type:bool]
        EnableTenantTokenCaching: ENC[AES256_GCM,data:gDIEbCU=,iv:sBg1eIwoAjxCKc26i12cwdDUcGfUXBhBB/GVVMl9QWA=,tag:yJ0RU7uvpgZ2Fc10Lwl0MA==,type:bool]
        TenantTokenCacheRotationIntervalDays: ENC[AES256_GCM,data:yg==,iv:41eqAR6zBkgBJvQegw4Y2rdkodlSNtQMWTqHCzOJf2c=,tag:H6stqnTAb4ie2+WdxYM16g==,type:int]
        BaseUri: ENC[AES256_GCM,data:Q2iP/1xszkyUk6uQL/NIbq4Y2ooLiTlQ1OqHH0qj+8ubLQ==,iv:bSMqr61YOvyKNxoNN3ySpZ4iECL2ZClx+U6EccFCrxU=,tag:fsxS9tVjNXQj1o33H1pfzw==,type:str]
        GroupId: ENC[AES256_GCM,data:bbuvPRv27xJtlLiNhTUu,iv:vll7cmR09sMlgkTE68pYUQVF+KVdnBMUt8yd0CODf0s=,tag:SrogjHV6tPQXN7xmai4SOw==,type:str]
        ProtocolVersion: ENC[AES256_GCM,data:dT8=,iv:qEo+2DYbnP4JJGFvXuxI1yLmj9KNTFaA9ccqAFdfd48=,tag:QIpw7KJdsm++X09oBiRM8Q==,type:str]
        GovernanceAdmin:
            ClientId: ENC[AES256_GCM,data:yV3kFTvgD8zfR8XpHoAYEe5ZeGSrFdVN+KJu15u7qTM=,iv:Og7vw7qDQ2lg2XoMVavrpUKIpn3tjesUw+3e2VAy5BI=,tag:1mnf9eFMv4wOyBn82kQm7Q==,type:str]
            ClientSecret: ENC[AES256_GCM,data:7OBDFyO2Z6VZd7Gh/g1wEMYVFN2FGHE7eFRr/lhjZCk=,iv:7wtO3TW4eGQLKV4Raujqo43pFmtFfsr6CEUjdwlXmvs=,tag:oiwjnYvMZ0n54rXlXzL4mQ==,type:str]
        TenantAdmin:
            ClientId: ENC[AES256_GCM,data:ISUQ4bDB1o+JymHV/iKzQH2J62iw4RRdg9w1bB+o/6o=,iv:O7liyOutfIc2mAPCAGIrSzmTuWDcjkq4pqOLRHPnRD4=,tag:XdZuh+PjtRfUq2EpleVfsQ==,type:str]
            ClientSecret: ENC[AES256_GCM,data:exZeYvKRTzys5AVolAoEHWvN6xZ72iODowoxIA0Wv6M=,iv:v3B9rpKU0jjvw7xOTDMrgQl7tMKvfhEtuKwfjUDGIs0=,tag:0v6cEWXj1P1bmLo2LiXyaQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-15T07:18:38Z"
    mac: ENC[AES256_GCM,data:BLBpGbQcQHlB8T80lJQYry9sxZvItquXhGcSIE/HHFkvFtzd/e2OKK+uy0iL/5grZLzlYMmRPH0FhMDB+HaorPoMw9P97VvTg7FIxAIlo+phG07Rz71fvjKNSmxORH3qE8goqkQQ+rgtyFCyqHqKPNMVtCgjucDg+dUjxsXAz2I=,iv:ig2qMwMvzD1u2gs4gUt5fjOTzSP9DKC8fMl9Z/gR4hE=,tag:DJG8J5SVqQrQlVQzYokMCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
