auth:
    password: ENC[AES256_GCM,data:y8+w5BcZ09s=,iv:HJp5sveyXzDWNh8DCLEhZxhGOpRYgwRQVjUI+wBOD88=,tag:p3R1Fen7Oq5tXIIxr1bO9A==,type:str]
    postgres-password: ENC[AES256_GCM,data:iXf50Z7H8dkooQ==,iv:FLv0eGN7Cr2fkRRKnakfdnDb4E+F1PqldESQIZCnJiM=,tag:G54yMzrbVN5TTx8FYYoB6w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: yoma-sso-dev
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T12:44:10Z"
    mac: ENC[AES256_GCM,data:PlrevX/tdDzTo0KTqr+v+KNWAqMa1hNHq2P9ndHa1x0YL/sz7LFj3yOittNEz4AchZAQvNSqjW0d+enINL6fZJRIWHodgoez1B72RY/ri/hV84NKRTXyTrIHZGrYh9OXGF0qrTygwcX02tRvAq0LDtxGTM9Wcblu8NRXmM8lHbY=,iv:yKJUIbW0uypJDvrMCRejkuMQdZv1nJTIGf/de+a/Zwc=,tag:xOWtlMdx3KSesZbnUl8wFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
