version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Maintain NPM dependencies for `/`
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - npm
      - dependencies
  # Maintain NPM dependencies for `web/youth`
  - package-ecosystem: npm
    directory: /src/web/youth
    schedule:
      interval: weekly
    labels:
      - npm
      - dependencies
      - web/youth
