version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Maintain NPM dependencies for `/`
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - javascript
      - dependencies
  # Maintain NPM dependencies for `web`
  - package-ecosystem: npm
    directory: /src/web
    schedule:
      interval: weekly
    labels:
      - javascript
      - dependencies
      - web
