version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Maintain dependencies for Node
  - package-ecosystem: npm
    directory: /src/web
    schedule:
      interval: weekly
