version: "3.9"
name: yoma-v3
services:
  yoma-web-admin:
    image: ${REGISTRY:-local}/yoma-web-admin:${IMAGE_TAG:-latest}
    container_name: yoma-web-admin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # CLIENT VARIABLES
        - NEXT_PUBLIC_KEYCLOAK_DEFAULT_PROVIDER=keycloak
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000/api/v3
        - NEXT_PUBLIC_ENVIRONMENT=local
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      # SERVER VARIABLES
      # KEYCLOAK_CLIENT_SECRET is a placeholder for future functionality, but is required by the app to run.
      - NEXTAUTH_SECRET=0vpMHSn0ufXwrEr1NKn6u1m+BKryJct5Cj7Jwt9mSSU=
      - KEYCLOAK_CLIENT_ID=yoma-web-admin
      - KEYCLOAK_CLIENT_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3001
      - API_BASE_URL=http://yoma-api:5000/api/v3
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/yoma
