# https://github.com/jdx/mise
[tools]
dotnet = "9.0"
helm = "3"
java = "temurin-17"
maven = "3.9"
node = "20"
tilt = "latest"

[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "30s" # Because azure is slow
