version: "3"
name: yoma-v3
# https://docs.docker.com/compose/multiple-compose-files/include/
include:
  - ./src/api/docker-compose.yml
  - ./src/web/youth/docker-compose.yml
  - ./src/admin/youth/docker-compose.yml
