environments:
  local:
    values:
      - namespace: yoma-dev
  dev:
    values:
      - namespace: yoma-v3-dev
      - arch: amd64
      - lifecycle: spot
      - tag: {{ env "TAG" | default "master" }}
      - ddInjectEnabled: false
  stage:
    values:
      - namespace: yoma-v3-stage
      - arch: amd64
      - lifecycle: on-demand
      - tag: {{ env "TAG" | default "master" }}
      - ddInjectEnabled: false
---
repositories:
{{ if eq .Environment.Name "local" }}
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
{{ end }}
  - name: simcube
    url: https://simcubeltd.github.io/simcube-helm-charts/
---
releases:
{{ if eq .Environment.Name "local" }}
  - name: ingress-nginx
    namespace: "ingress-nginx"
    chart: ingress-nginx/ingress-nginx
    version: "4.8.3"
{{ end }}
  - name: mssql
    labels:
      app: mssql
    namespace: {{ .Values.namespace }}
    chart: simcube/mssqlserver-2022
    version: "1.2.3"
    set:
      - name: edition.value
        value: Developer
      - name: acceptEula.value
        value: "Y"
      - name: sapassword
        value: "Password1"
      - name: image.repository
        value: ghcr.io/didx-xyz/mssql-server
      - name: image.tag
        value: 2022-latest
    values:
      - service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    secrets:
      - ./helm/mssql/conf/{{ .Environment.Name }}/secrets.yaml

  - name: keycloak
    labels:
      app: keycloak
    namespace: {{ .Values.namespace }}
    chart: ./helm/keycloak
    version: "0.3.2"
    values:
      - ./helm/keycloak/conf/{{ .Environment.Name }}/values.yaml
    secrets:
      - ./helm/keycloak/conf/{{ .Environment.Name }}/secrets.yaml
  - name: postgresql-keycloak
    labels:
      app: postgresql-keycloak
    namespace: {{ .Values.namespace }}
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: "13.2.2"
    set:
      - name: fullnameOverride
        value: postgresql-keycloak
      - name: auth.username
        value: keycloak
      - name: auth.database
        value: keycloak
    secrets:
      - ./helm/postgresql-keycloak/conf/{{ .Environment.Name }}/secrets.yaml

  - name: yoma-api
    labels:
      app: yoma-api
    namespace: {{ .Values.namespace }}
    chart: ./helm/yoma-api
    version: "0.1.0"
    set:
      - name: image.tag
        value: {{ .Values.tag }}
    values:
      - ./helm/yoma-api/conf/base/values.yaml
      - ./helm/yoma-api/conf/{{ .Environment.Name }}/values.yaml
      - nodeSelector:
          kubernetes.io/arch: {{ .Values.arch }}
          node.kubernetes.io/lifecycle: {{ .Values.lifecycle }}
    secrets:
      - ./helm/yoma-api/conf/base/secrets.yaml
      - ./helm/yoma-api/conf/{{ .Environment.Name }}/secrets.yaml

  - name: yoma-web
    labels:
      app: yoma-web
    namespace: {{ .Values.namespace }}
    chart: ./helm/yoma-web
    version: "0.1.0"
    set:
      - name: image.tag
        value: {{ .Values.tag }}
    values:
      - ./helm/yoma-web/conf/base/values.yaml
      - ./helm/yoma-web/conf/{{ .Environment.Name }}/values.yaml
      - nodeSelector:
          kubernetes.io/arch: {{ .Values.arch }}
          node.kubernetes.io/lifecycle: {{ .Values.lifecycle }}
    secrets:
      - ./helm/yoma-web/conf/base/secrets.yaml
      - ./helm/yoma-web/conf/{{ .Environment.Name }}/secrets.yaml
---
helmDefaults:
  timeout: 180
  wait: true
  atomic: true
  cleanupOnFail: true
  createNamespace: false
