environments:
  local:
    values:
      - namespace: yoma-dev
  dev:
    values:
      - namespace: yoma-v3-dev
        arch: amd64
        tag: {{ env "TAG" | default "master" }}
        ddInjectEnabled: false
        ddProfilingEnabled: false
        postgresEnabled: true
        redisEnabled: true
  stage:
    values:
      - namespace: yoma-v3-stage
        arch: amd64
        tag: {{ env "TAG" | default "master" }}
        ddInjectEnabled: true
        ddProfilingEnabled: false
        postgresEnabled: false
        redisEnabled: false
  prod:
    values:
      - namespace: yoma-v3-prod
        arch: amd64
        tag: {{ env "TAG" | default "master" }}
        ddInjectEnabled: true
        ddProfilingEnabled: false
        postgresEnabled: false
        redisEnabled: false
---
repositories:
{{ if eq .Environment.Name "local" }}
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
{{ end }}
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: didx-xyz-config-cli
    url: git+https://github.com/didx-xyz/keycloak-config-cli@contrib/charts?ref=init-containers&sparse=0
  - name: simcube
    url: https://simcubeltd.github.io/simcube-helm-charts/
---
releases:
{{ if eq .Environment.Name "local" }}
  - name: ingress-nginx
    namespace: "ingress-nginx"
    # https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.10.0"
{{ end }}
  - name: keycloak
    labels:
      app: keycloak
    namespace: {{ .Values.namespace }}
    chart: ./helm/keycloak
    version: "0.3.2"
    values:
      - ./helm/keycloak/conf/{{ .Environment.Name }}/values.yaml
      - keycloak:
          statefulsetLabels:
            tags.datadoghq.com/env: v3-{{ .Environment.Name }}
          podLabels:
            admission.datadoghq.com/enabled: {{ quote .Values.ddInjectEnabled }}
            tags.datadoghq.com/env: v3-{{ .Environment.Name }}
    secrets:
      - ./helm/keycloak/conf/{{ .Environment.Name }}/secrets.yaml
  - name: postgresql-keycloak
    labels:
      app: postgresql-keycloak
    namespace: {{ .Values.namespace }}
    # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: "14.3.1"
    installed: {{ .Values.postgresEnabled }}
    set:
      - name: fullnameOverride
        value: postgresql-keycloak
      - name: auth.username
        value: keycloak
      - name: auth.database
        value: keycloak
    secrets:
      - ./helm/postgresql-keycloak/conf/{{ .Environment.Name }}/secrets.yaml

  - name: postgresql
    labels:
      app: postgresql
    namespace: {{ .Values.namespace }}
    # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: "14.3.1"
    installed: {{ .Values.postgresEnabled }}
    set:
      - name: fullnameOverride
        value: postgres-yoma
      - name: auth.username
        value: yoma
      - name: auth.database
        value: yoma-dev
      # - name: primary.extendedConfiguration
      #   value: |
      #     log_statement = 'all'
      #     log_min_duration_statement = 0
    secrets:
      - ./helm/postgresql-yoma/conf/{{ .Environment.Name }}/secrets.yaml

  - name: redis
    labels:
      app: redis
    namespace: {{ .Values.namespace }}
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: "19.1.0"
    installed: {{ .Values.redisEnabled }}
    values:
      - fullnameOverride: redis
        architecture: standalone
        auth:
          enabled: false
        master:
          count: 1
          persistence:
            enabled: false
        replica:
          replicaCount: 0

  - name: yoma-api
    labels:
      app: yoma-api
    namespace: {{ .Values.namespace }}
    chart: ./helm/yoma-api
    version: "0.1.0"
    set:
      - name: image.tag
        value: {{ .Values.tag }}
    values:
      - ./helm/yoma-api/conf/base/values.yaml
      - ./helm/yoma-api/conf/{{ .Environment.Name }}/values.yaml
      - nodeSelector:
          kubernetes.io/arch: {{ .Values.arch }}
      - env:
          DD_PROFILING_ENABLED: {{ .Values.ddProfilingEnabled }}
        deploymentLabels:
          tags.datadoghq.com/env: v3-{{ .Environment.Name }}
        podLabels:
          admission.datadoghq.com/enabled: {{ quote .Values.ddInjectEnabled }}
          tags.datadoghq.com/env: v3-{{ .Environment.Name }}
    secrets:
      - ./helm/yoma-api/conf/base/secrets.yaml
      - ./helm/yoma-api/conf/{{ .Environment.Name }}/secrets.yaml

  - name: yoma-web
    labels:
      app: yoma-web
    namespace: {{ .Values.namespace }}
    chart: ./helm/yoma-web
    version: "0.1.0"
    set:
      - name: image.tag
        value: {{ .Values.tag }}
    values:
      - ./helm/yoma-web/conf/base/values.yaml
      - ./helm/yoma-web/conf/{{ .Environment.Name }}/values.yaml
      - nodeSelector:
          kubernetes.io/arch: {{ .Values.arch }}
      - env:
          DD_PROFILING_ENABLED: {{ .Values.ddProfilingEnabled }}
        deploymentLabels:
          tags.datadoghq.com/env: v3-{{ .Environment.Name }}
        podLabels:
          admission.datadoghq.com/enabled: {{ quote .Values.ddInjectEnabled }}
          tags.datadoghq.com/env: v3-{{ .Environment.Name }}
    secrets:
      - ./helm/yoma-web/conf/base/secrets.yaml
      - ./helm/yoma-web/conf/{{ .Environment.Name }}/secrets.yaml
---
helmDefaults:
  timeout: 180
  wait: true
  atomic: true
  cleanupOnFail: true
  createNamespace: false
