# https://github.com/jdx/mise
[settings]
minimum_release_age = "7d"

[tools]
dotnet = "10.0"
helm = "4"
java = "temurin-17"
maven = "3.9"
node = "24"
pnpm = "11"
tilt = "latest"

[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "30s" # Because azure is slow
