auth:
    password: ENC[AES256_GCM,data:rnhT3frWcyqN,iv:5guvHvj6+o68FVU6AiL111VlgOmHB/it8nM0v6JoGa0=,tag:Zvt8ZjR7WwXKxQllyfVABg==,type:str]
    postgresPassword: ENC[AES256_GCM,data:Uxso2QJCcpNiFQ==,iv:IcQyPCVz0F3eDk+jAhBOKYqjxqIg6ldgCHzXbYgQJWU=,tag:vrS4E0DTbytgEg1Q4ngSzg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: yoma-sso-dev
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-30T11:21:24Z"
    mac: ENC[AES256_GCM,data:Tyjv2ovgmKq42AxN1yLTcrEeTTslprK+jfy9lQDPWgu/gpvLcjcQh5CRqjhDeprP+5rwHwR8/Jio5vBo/BlyAlaIGfv/UX1VaBgK4f4nf642lhwdN+JUouOr7XJpbo1+9amvE4qU7tatsiD2oFKJW5EqbjQ+ElO2RQ2X+ebQstg=,iv:2FgAe2UFU5N+TmwBGRMV6b2/RFZcsqoRvhK800E3ADM=,tag:6Es83R6WOsy2lTFyxxd5lQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
