image:
  repository: ghcr.io/didx-xyz/yoma-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://v3app.dev.yoma.world"
    rules:
      - host: v3api.dev.yoma.world

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__SQLConnection: "Data Source=mssql-mssqlserver-2022,1433;Initial Catalog=yoma-dev;MultipleActiveResultSets=true;User ID=sa;Password=Password1;TrustServerCertificate=True;Encrypt=True"

appSettings:
  fileName: appsettings.Development.json

volumes:
  - name: app-settings
    secret:
      secretName: yoma-api

volumeMounts:
  - name: app-settings
    mountPath: /api/appsettings.Development.json
    subPath: appsettings.Development.json

postInstallHook:
  enabled: true
  image:
    repository: ghcr.io/didx-xyz/mssql-server
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 2022-latest
  command:
    - /bin/bash
    - /init/post.sh
    - mssql-mssqlserver-2022
    - sa
    - /init/post.sql
  env:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: "Password1"
    SQLCMDPASSWORD: "Password1"
  nodeSelector:
    kubernetes.io/arch: amd64

  volumes:
    - name: init
      emptyDir: {}

  volumeMounts:
    - name: init
      mountPath: /init

  initContainers:
    - name: download-sql
      image: docker.io/busybox:stable
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |-
          cd /init
          wget -O - \
            --header="Authorization: token ${GITHUB_PAT}"\
            --header="Accept:application/vnd.github.v3.raw" \
            https://api.github.com/repos/didx-xyz/yoma/tarball/master | tar xz
          cp -v ./didx-xyz-yoma-*/src/api/cicd/scripts/sqlserver-init/* /init/
          rm -rf ./didx-xyz-yoma-*
      env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: keycloak-github-pat
              key: github-pat
      volumeMounts:
        - name: init
          mountPath: /init
