image:
  repository: ghcr.io/didx-xyz/yoma-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://v3app.dev.yoma.world"
    rules:
      - host: v3api.dev.yoma.world

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  # ConnectionStrings__SQLConnection: "Host=postgres-yoma;Port=5432;Database=yoma-dev;Username=postgres;Password=P@ssword1;SslMode=Prefer;Trust Server Certificate=True;Include Error Detail=true;"

appSettings:
  fileName: appsettings.Development.json

volumes:
  - name: app-settings
    secret:
      secretName: yoma-api

volumeMounts:
  - name: app-settings
    mountPath: /api/appsettings.Development.json
    subPath: appsettings.Development.json

initContainers:
  - name: check-postgres
    image: postgres:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |-
        until pg_isready -h postgres-yoma -p 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL is up and running."

postInstallHook:
  enabled: true
  image:
    repository: postgres
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "16"
  command:
    - /bin/bash
    - -c
    - "/init/post.sh /init/post.sql"
  # command:
  #   - /bin/bash
  #   - -c
  #   - "PGPASSWORD=$$POSTGRES_PASSWORD psql -h $$PGHOST -U $$POSTGRES_USER -d $$POSTGRES_DB -f /init/post.sql"
  env:
    PGHOST: postgres-yoma
    PGPASSWORD: P@ssword1
    PGUSER: yoma
    PGDATABASE: yoma-dev
    PGPORT: "5432"
  nodeSelector:
    kubernetes.io/arch: amd64

  volumes:
    - name: init
      emptyDir: {}

  volumeMounts:
    - name: init
      mountPath: /init

  initContainers:
    - name: download-sql
      image: docker.io/busybox:stable
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |-
          cd /init
          wget -O - \
            --header="Authorization: token ${GITHUB_PAT}"\
            --header="Accept:application/vnd.github.v3.raw" \
            https://api.github.com/repos/didx-xyz/yoma/tarball/postgresql-helm | tar xz
          cp -v ./didx-xyz-yoma-*/src/api/cicd/scripts/postgressql-init/* /init/
          rm -rvf ./didx-xyz-yoma-*
      env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: keycloak-github-pat
              key: github-pat
      volumeMounts:
        - name: init
          mountPath: /init

readinessProbe:
  enabled: true
