image:
  repository: ghcr.io/didx-xyz/yoma-web
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

env:
  NEXT_PUBLIC_API_BASE_URL: https://v3api.dev.yoma.world/api/v3
  NEXT_PUBLIC_ENVIRONMENT: dev

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    rules:
      - host: v3app.dev.yoma.world
