appSettings:
    AppSettings:
        AppBaseURL: ENC[AES256_GCM,data:0t35F0e5VTGjrvCkujDn2ywVmMb/mw==,iv:D5B0KOpJW2N03XzKU03T/J5OY/cPQ92IM5rGt79Sw4A=,tag:FWWX4nRRJnwJRU89elrvlg==,type:str]
        AllowedHosts: ENC[AES256_GCM,data:UA==,iv:b2jTfAVIg5m5UXsDMxO7Vb0aaOXVzUfrjKW3jWW9sQI=,tag:mdAAfC6OWEp5ETVb/FDGXA==,type:str]
        AllowedOrigins: ENC[AES256_GCM,data:C+bgmjjY8hS/z5pEsSAD+RTntDlJIFBfaL6e/yh3b9gVf/Qy72kDVKRTmYljXOoKf+xAeIEHC4mlCoDRxI0OjEcW,iv:z7+95xD9yuVWigUg1B/NZiMuWCTYkuBwqpXM9rV3L1I=,tag:wLxlsGM6MZeeQ976RePGdw==,type:str]
        SSIIssuerNameYomaOrganization: ENC[AES256_GCM,data:1UBhaKVM3/BzQMC7dZkEPR2IrEaApCGxtHjjM2FyAg==,iv:hCas3b8m69wkSbV88r8UFc4Te3m2yzPOxL7rPlmshPo=,tag:++aG0GuZTB9kg2ZsVEB3HQ==,type:str]
        SSISchemaFullNameYoID: ENC[AES256_GCM,data:Fw+km5h8tCFDXPXW,iv:j4jLOcvrkidYN/GwkiT7aermN+tWTW945mdHNOoigx4=,tag:oi14XSI4P8cjJYjxxu22sQ==,type:str]
        TestDataSeedingEnvironments: ENC[AES256_GCM,data:SFs+lLIw/lLhZO+bivrvmzse,iv:npnOtJQrfKnOkNmonfKQ/Ejrblv+ttreUrF8hk298pE=,tag:CDzqfx4+h7H6iR9GZkJKgQ==,type:str]
        Hangfire:
            Username: ENC[AES256_GCM,data:SbQ2BMQ=,iv:F3bPNhN5LtbYqp2I3mriCjms8KBjpgK823U0pB741Fc=,tag:W/mahg/RJF0Va+hjAU9oQw==,type:str]
            Password: ENC[AES256_GCM,data://vfHxEtqwopWZbX1G4YfgREd53o/Hrj7RGqIzeZKgY=,iv:MnOoPwRRN9P4sbHx29frBm+Ivh/r116rvz+BoI5rZEc=,tag:hQ+DNEz+5yhr2GDX9PWkWg==,type:str]
        Sentry:
            Debug: ENC[AES256_GCM,data:DXkL6tY=,iv:7M4cbLwLTdit0azXMBcVZbY2B92pY6eY2BzVAShHaKo=,tag:r1mtReF8+nf/GFrxZDCAQQ==,type:bool]
        LaborMarketProviderAsSourceEnabledEnvironments: ENC[AES256_GCM,data:hBIBvNAuvWtuPg==,iv:g1UsfIlYmTG6EGzFGXIb/OvgP/jGTUHAvpeDWTspUlo=,tag:2LY/Q7zxot6YJNEfm8AtSA==,type:str]
    Logging:
        LogLevel:
            Default: ENC[AES256_GCM,data:6G0eqoGXJyqWlOk=,iv:eLJBNz6cK6fgv3MIIS9bRZsajwNpeFzq6ocJkr7D+tQ=,tag:QEKLU+wAIcVrHKSESLrTgw==,type:str]
            Microsoft: ENC[AES256_GCM,data:NVrGkaxtdg==,iv:FF2UOvDB+Ib9isoq+8xvY4KJTNJ5ggmG/oXgtgrTmPQ=,tag:kAvZCTNsip7CTD9DBfDCBw==,type:str]
            Microsoft.Hosting.Lifetime: ENC[AES256_GCM,data:MvHFiQosGfG+BEg=,iv:NoBGff+owSEVBpGROj5GkqM1A2AwqA9Q+Lg+9FC05X0=,tag:xvYkLJuZDjOXcRZHitwcAQ==,type:str]
    AWSS3:
        Buckets:
            Public:
                AccessKey: ENC[AES256_GCM,data:FG9Hn71j0THTkInevqdZL9Qrsac=,iv:tw2rIOffG3IkKgdM8cLkSIBnfZuNMJHn2mXULPVWK+M=,tag:padj2xqbhCBoelAf2fS8Mg==,type:str]
                SecretKey: ENC[AES256_GCM,data:RhwHslI+kjNXOy4d+KhU8yy8TZhexUcl739CHbgSk4aUqLXNo1FjHw==,iv:hwojinvkZg6wHq5n4zT6V6JMoZpA6gAgcTfuv8JW4wU=,tag:epi7Jj0ImqKlnPFwvJZjvw==,type:str]
                BucketName: ENC[AES256_GCM,data:Teat1uk7lQxkEIK1RNImKjgxK5QU+A==,iv:7opbdZIG0YfuiM2jiFnLRky1rXsKQaNUT/Lvs06TkHY=,tag:J86gBOHUlAuHY1ODGa+kvQ==,type:str]
            Private:
                AccessKey: ENC[AES256_GCM,data:I4tuDeTS5vxGImXd4Pb5J6c8BIM=,iv:JFO73bIG//fw1CJOWAhYeGzUCa7pil2uz6DWPe2HRTg=,tag:QVBZVz1f78W711IlQedqPQ==,type:str]
                SecretKey: ENC[AES256_GCM,data:glDsW1dkZaQOZjQuhmYZQStZ0sYh3yGCmrZ11SncsJ39HuBe17g2fg==,iv:tcpekNkr2pA8mujhO5GhQzL7XJiuT37UNvnE9ye9e6Q=,tag:XnBm0OmMw6FlC6lJECO9EA==,type:str]
                BucketName: ENC[AES256_GCM,data:dqckR2HEBRR6Yi6HyhYd1jwm062jBMk=,iv:mocivdFoXNGALwNvPuwCVy4h1csYp9D2W2wN07SAdqI=,tag:sz5fzo3nOjB4LNxw4Fkdag==,type:str]
    ConnectionStrings:
        SQLConnection: ENC[AES256_GCM,data:SS4fs0SkjLFUj44sbXUEa8egpCczslzbH69lMi5TiXdG8DUeOHQPAM1atiHduLUhSU7BuBuQNjd0rlvZGWfAZsu1f1UgSfjBBnD6gC8VrdYqEmMSMRT2jHmc8cQk/CAFFwHjwo+FNa9SZB3gGVoHJYQ2qUW+kfq3uVy9nGrc8CGd1RINjaR+yl3Ezbqqdbbr6hgldRbzgu3V8V0TCaRCpKGi5fZfJNGSBWX4cdvNTMhIU/TqYLreXLTfvK/qN6a4r24Vr6HXls8wjimyxyXWIQyNryckwwH4Rxw2jsnaIkjhIZrrbAUP4sm30RcIGvlhDX/hjI5S08M+imGCwwS0edm+4BPrK0bZoQ==,iv:rnW27WqCJgJdR7MX2B8iAwZ98U1/tw5EemQRu7pSJr4=,tag:t/vTGABUYtoAWY/G38pGEw==,type:str]
    KeycloakAdmin:
        Admin:
            Realm: ENC[AES256_GCM,data:26CPf0qV,iv:3SUhgiT03LNqzduCVe3Yx1+iFfXS5K25DfRVXOzlshI=,tag:fe4gz9anv7xEP2jy408vrw==,type:str]
            Username: ENC[AES256_GCM,data:+mZWT/Uw7lKdlZQ=,iv:BZ6r45NOEffbMSavgJTywG381BpSuy6VusTCPB4o3Qo=,tag:HIW0y6gMJ/Gdsh4CA+zrjg==,type:str]
            Password: ENC[AES256_GCM,data:UaysIL2AetJg/C/ZKgcpP722YjFP6brkefRBvXxjy102N34WHzVHKo/HdXoQ9L+233r/gpxmaxLOG+nb+bLEtA==,iv:VR2GNVwo0oG2KbHBWaDAORRFS1DxoGA67Q+6ChBXSbo=,tag:qtDQilDNTnB6zoh0e/rAVw==,type:str]
        WebhookAdmin:
            Username: ENC[AES256_GCM,data:f0ZABJDBqQ==,iv:YFuhJIAH4M/Wu39LCXdb107o/TlIkBHzCWRJrK4HHzQ=,tag:vnh6g495wzWKly8PseVlPw==,type:str]
            Password: ENC[AES256_GCM,data:zhuMzidzJMgT97pknm3AxH03SqjgxK2711GsjqERMdg=,iv:n+UFMSirwS8lnOKluTzrhG1abkDlyCRQVdTjbd7Qxkw=,tag:cwjIef/kkuuN5ooDIYDNkw==,type:str]
    Keycloak:
        realm: ENC[AES256_GCM,data:+o5X0Q==,iv:7KIbgq03FjkGoQpr7pgD8TTrYFN0NPmXR7j9fsureNI=,tag:OaKK54Lk55hJFAk0c8msRQ==,type:str]
        auth-server-url: ENC[AES256_GCM,data:/vMva7N6hXMwXKb+TP7QalZQ+VKfEdg=,iv:R3YogrU8BppLAsSDD0H/fv+eLKwk+mBo9YUSF4+I58w=,tag:o/BgakTnOCurVqBhA8AvdQ==,type:str]
        ssl-required: ENC[AES256_GCM,data:Ec6/SA==,iv:rVCUV3FOqrdpWAKhmrquHfqcM9KebGN1qiFf4j8XJ0Y=,tag:TjHep/ZXJHGH1KRASm6Ljg==,type:str]
        resource: ENC[AES256_GCM,data:yzlpqEjgjN0=,iv:igYrFzj//st4drPnfcqjIWNhKy1R2duh8Av7Wr6so/4=,tag:u3MkXTrJo1ZPJkum/Fq1qA==,type:str]
        verify-token-audience: ENC[AES256_GCM,data:qbdDsA==,iv:ZcKzcO7zFsjW/XH66zGE2NhETWKPE2d3gxsfSgmoEF8=,tag:cgM6RbWT0qu+XXUMDczqiQ==,type:bool]
        credentials:
            secret: ENC[AES256_GCM,data:z1hSKt4Au8aU8iGxVBXdRPnYsqN+M3YpVISNYa5ufYId8H/Bomu7xsVjIYeoemmf2hv6ZdixoYQ1ywDlNBUfPg==,iv:+L8Thf6D5a81vBHsBnJObO4wTc6CFJZgtaFlQI08GjM=,tag:IsCeQyDNofZ5pmDabFwM5g==,type:str]
        use-resource-role-mappings: ENC[AES256_GCM,data:3Xh1MQ==,iv:Lb4cnvoOJ+a9y+A+xcL7khWS1ZMJ0McxfwSf9GSvJhs=,tag:dhkAJ/S6vhTughMhnWWfLA==,type:bool]
        confidential-port: ENC[AES256_GCM,data:dg==,iv:YYmRCfsJYvETRicdXOVdX7Xuj8x9dRZ4vTmfSBpBjJ8=,tag:XzNyJGT0W8BrbwNxc5Du5Q==,type:int]
    Sentry:
        Dsn: ENC[AES256_GCM,data:jSoUOUu1d0l60dCcTvhc0ejV6YkeEk/ns7MRLLx0RJ4U1+8sRMd1KDVYtZ6d1nt896xxZboVoeic/zVqOK4KHQxC1Xll4scXgok3BRv2whyQYw==,iv:JmDmyaa5dK1KtitD9+B4AMh9KBQB3J5fZsTxwSAIX6o=,tag:zOktfLVJZAOYBQeIbV+CIQ==,type:str]
    Emsi:
        ClientId: ENC[AES256_GCM,data:T7wUHbs=,iv:ipA9poModlIVZGhJ6xYFJo7bIScNUKDMJRr1ueAyITc=,tag:iNef5yeHKMxLqUCQu3+nxg==,type:str]
        ClientSecret: ENC[AES256_GCM,data:woDRfz2vCr9WT200SqfL,iv:CMF6eknJDxbpc/ynztH3tj40amEtUrTX5w+BnAhBuGk=,tag:/Ckjw0KQqqpxrGPfT+z+UQ==,type:str]
    SendGrid:
        ApiKey: ENC[AES256_GCM,data:MXBNelEbLfWR5ULzf4Cm8fcMPB4LYXbQTKYhB1hDBXuRQRYQKjWOz1PKJmTMT5q3V49MwZ+6b5LJf6MeAsIgdghsR/Fi,iv:CigADe33KwLiUxV8v7PWQly5kqtT9ght22ssvVMTw6c=,tag:71/7Sc40uq6kjrNWyF0xNQ==,type:str]
    Zlto:
        Username: ENC[AES256_GCM,data:WnjmYgGGhjNYWTsIKo8=,iv:3AnzC5FYoIvaC9QjQh0UZ5yOSwIB+5Zhj9+VJVVeVsU=,tag:W+jaJ3V9JHMeQGJVadPeqA==,type:str]
        Password: ENC[AES256_GCM,data:iTWk0bkZUlY=,iv:TRmWaOQX3NjeArVw5oSL4J/MNvXulVFEeWtQv52g1l4=,tag:MIs7xpDlmN4UVdVv38SB2Q==,type:str]
        ApiKey: ENC[AES256_GCM,data:TXTRa9oll5cYGojuE0IhBkgNjj+hCrdVKEmUo8Bl+J4Z84Ew,iv:AE1IwmafvcS/yIQJeEebO7JGPuzn6KODb0+xhS2+E2s=,tag:JY+qIziqT3YzspqLs1Od+A==,type:str]
        Partner:
            BaseUrl: ENC[AES256_GCM,data:LUNmSs2MrtGLn34XamjCG5FKsvldJxlcm7rU,iv:eUjFu9ZguWT5oyr3Is/AEcouPBHhRlsgsaHcdlkN9Ao=,tag:jp9fewgLhAZT3e8MVUbpfQ==,type:str]
        Wallet:
            BaseUrl: ENC[AES256_GCM,data:c7Nl8gDWzJPvFHWLoMX2wnSVf+ZnEl41LA==,iv:pH0fP97Wte6ZQoEEvDfjMOfMYvY+RyghNTxPVj/Caig=,tag:1UzJ93XFO6u8aofWSmL6BA==,type:str]
        Store:
            BaseUrl: ENC[AES256_GCM,data:wMKUIPL2EvNqPAK4Fc9NOR6laRlFK6Oa,iv:6Len6SpAJHAeBHkoLUKASLyfy2nwXDWheVLbJ2ef3MM=,tag:pwjzOSG2cX3FgB9TR87UkA==,type:str]
            Owners:
                - CountryCodeAlpha2: ENC[AES256_GCM,data:ElQ=,iv:gSb8er+ou3IZ7hB5rmzyl+0HmBRSPKeVK3E5K9PMOdc=,tag:1G3cziwVETWC8iSpOWzi5Q==,type:str]
                  Id: ENC[AES256_GCM,data:LOhTyrArvETHChSc+DCL91vvTjnBrivZtVXOpuKrSRZq/pOz,iv:oKXm5mvPxjSzguEcBfAV/2DStFvi7Q7lGqSXbgs3/WQ=,tag:31WRiNLRtjwyEXP27u0NKg==,type:str]
                - CountryCodeAlpha2: ENC[AES256_GCM,data:Zyo=,iv:NVvln//7Bc49AZ/ih0/q5exM1QOao8L5sc3tHM0k3MA=,tag:fqpUIpIpp+PhvrPGhgWozA==,type:str]
                  Id: ENC[AES256_GCM,data:ZCxaOP1XFk3paQ4LcLBFxM+EYTHwbTUD11B/LNftaN3g4qg2,iv:7i5l8JUDJO7caz3IvNlYwmVWaQL1L/fUKJRe3EEW6pQ=,tag:rcQGdPFLpH6mJiMfcGdE6w==,type:str]
                - CountryCodeAlpha2: ENC[AES256_GCM,data:rUg=,iv:KD7pbNAyzV1dmwmlkAb54DJy7wi/M+pzS5GUdSI2x9Y=,tag:pldcrqBaswTBOrVYXi4r+A==,type:str]
                  Id: ENC[AES256_GCM,data:y53sRyEdiaVuFQko7uN2voJe8bhoeR31lPPe+Bz/IhStbZAH,iv:jKARpKA6yTzij9ExM+rfCWsmO4lFLczC6OM//YvqaRU=,tag:LUtMi28KcBMbFUDg33iDGg==,type:str]
                - CountryCodeAlpha2: ENC[AES256_GCM,data:EP4=,iv:EuurRnBJXBptr27J+tmo11RgPbZC1rZqugnZ6in8hvk=,tag:lNYm7r763oNc3qkCKrBKMw==,type:str]
                  Id: ENC[AES256_GCM,data:D3qEiqzxtqth1M5RpY3B3kKDxQRgl98JnpLGKfimqTtN/JKG,iv:RI7NeGjN5wgE65MYKCQbSu3GTkF71JdOVCX9ol70qgM=,tag:JohZRQmTJOwydaOkIdbfNQ==,type:str]
        Task:
            BaseUrl: ENC[AES256_GCM,data:x97scd7B3RC065hqWbWxRxS7DnGoMGg=,iv:QHDVy+muCW+hI4eu3Z4swxuBOEWbHh89Z457BPpVpCA=,tag:Pi7g7JHhkH3aBb7HV84b6g==,type:str]
    AriesCloudAPI:
        DebugOutput: ENC[AES256_GCM,data:FcPhBiw=,iv:g4O+NcYGDDk06kfNSPYI4CjbjPgfAWVMlMt7iUdwi70=,tag:ztBHxNo8ENHQix2DMTpj6Q==,type:bool]
        EnableTenantTokenCaching: ENC[AES256_GCM,data:rsYKSgs=,iv:7uc1ru2LMuw4NnLvNxfBceBMem9AjQIkYCnL1zU+b7k=,tag:VhlfMU/l32pbOH8ROSr7yw==,type:bool]
        TenantTokenCacheRotationIntervalDays: ENC[AES256_GCM,data:TQ==,iv:siPewvMUMRAe1Mkvna/LwulmBh9tB0NnR5nWiQoTZRQ=,tag:aaFC4Vh0+Uqwow93hFFhgw==,type:int]
        ProtocolVersion: ENC[AES256_GCM,data:upE=,iv:jl4ZUJw7Qcj/BUM1BnhNsLNwqH9qDsRehFXmdD3Sx8w=,tag:QkdLVDx0ptSIUjU7aInaGw==,type:str]
        #ENC[AES256_GCM,data:f6j8MapUDgP8ijVRJt0z9Y24hBOvdUrWca4EX9xcL7TB,iv:Dh+8kFXept+jCcdyMxNI9SuLv7LihPOrvHgm+XasYOc=,tag:xAMo5hPXOjBqOoaPC+UbRQ==,type:comment]
        BaseUri: ENC[AES256_GCM,data:Uh6cnq1XgD2nrwdly3mZ0YhMnVWQwbA6WD6R1esomtwF0g==,iv:jTTvzHTBD7NYs1azMa7XN4rOM71yeBJ9hBylUyM5ZjI=,tag:HKWtAFSmmduCtmqAJkevAQ==,type:str]
        GroupId: ENC[AES256_GCM,data:J29QqIX2UxJn,iv:yV/2ciQry2OoCnWwIB2mMDybbbngGiEZFrQqcyuQfXg=,tag:vo5ADEDWYVfkS3fonPMSAA==,type:str]
        GovernanceAdmin:
            ClientId: ENC[AES256_GCM,data:yU+h0bKvYtwb5nf1sVHignsHDQedr6rQDmfhdBd/7lg=,iv:E1L9yyUseobehdN8j6JLV1t5mnUmHcdk5EGl8lBzLEU=,tag:tIqLolsucG7iJtpTXfwJjg==,type:str]
            ClientSecret: ENC[AES256_GCM,data:sUYk71g3SNcjW/z1vGekQ1dcUFC2+wsPjlCKaoqUKAQ=,iv:RLoIjhIPthnB4O1f1b9WXWh9f4cSEq+0Abmwc3C2ge0=,tag:meqylwOPC1kCy2OsVKzpzQ==,type:str]
        TenantAdmin:
            ClientId: ENC[AES256_GCM,data:yatj3nmIK6D8D8T/CqHrPRe8tXx1uBYmfnZpBanwA94=,iv:XFa1DPm/9DA09Lbh6Y3FfLNVbsDiYTPDiN651U5WC5w=,tag:6i+Y7ZNE9C7VJJFc97/GIQ==,type:str]
            ClientSecret: ENC[AES256_GCM,data:8fBcbNoHOadXC0KWU+izeFJiWn3aZxMUINUhTHtoRfc=,iv:XPWGzwUAVP3KijbKlklbJsPvM6Z2GnuDszqr/CwSXZ4=,tag:i3GkZaonlfVUK/x6lmqlUg==,type:str]
#ENC[AES256_GCM,data:DfoWJRkjSbyQNKAKLKJrKOPpopz4+mpI5JVZYe3F2eAO,iv:KmjVSnaj/mWz2zcsH77lyKGsPCpOn9PTWYWaIl/kDQk=,tag:5XS/9JjrJFawb/XsgF+E9w==,type:comment]
#ENC[AES256_GCM,data:rQ5T35hp/Lkvaah764KPIoMP5Diy0jSVp1nG86U2e8gi4H0T2qQwS04Puhb1+fPC5anb,iv:D7T+2CZTnIdid1lXGgyMw3EpMbWLrO/Y4ZkUmsRWQiI=,tag:m97XLvxwCGR9uMmk3bAb2A==,type:comment]
#ENC[AES256_GCM,data:z2qu/nLcOpDq5Pb1gC65sz9UdFZd2/Mmz6c8xK4Kw2o8kgk/zRCb02DItRS39DsrJ4X94W4iyh2Px9j+aZCClw5079VzVzgoP59EL4Or03Fe8w==,iv:zN/31tArf07eHXeJnYeu4Epi8unhOTRPuBYMW8xG5Gs=,tag:T/g5gPItpNtKFRt14t2HUg==,type:comment]
#ENC[AES256_GCM,data:wS1pLxk+EFmr8UThemUfPwHur7aLEas3gpaBm4aCUcRpIQ70+A==,iv:u04B0BWM2rakhsUBCsjGq9eh8Zl0oyKUS7CdUjpvzmw=,tag:pt3cirrTMD1GhPj9HfHmMw==,type:comment]
#ENC[AES256_GCM,data:lBd56XUSEsaLZTjHpJg=,iv:/fAizoRm+MZl34xYHriaUV+kVAAkTUAkprS9o7Cbocg=,tag:wb2Drvd6hYX+/ULGbFOqGw==,type:comment]
#ENC[AES256_GCM,data:loBSUO+Z/l8HvAKhNiYdwQE=,iv:/0ixWu5gCrV2lR1B/sM42M53SgAJ3PSqw2AEsllJyEo=,tag:GIgyBiobQkzUqBiBUoE9bQ==,type:comment]
#ENC[AES256_GCM,data:PQUVtziTF7Sl4ZMG5xoKRyX0fn7xQghZKdnINawEmva7isM83DCd0u1GxG7+yAI=,iv:YJMlP5MDWy3rA5dHTXot1ymNoG1Hf3ps+bcUlmRm2Bs=,tag:G8mrmVbk5oy5w1oXMoBIeQ==,type:comment]
#ENC[AES256_GCM,data:rTJeoPbhceLNb6EXGfiGeHGDLPzbKm7FgQhG/Ln2m4JSf7r96cRCa4jf9cRe3feX0o96,iv:l7W0Ub/jFLEQhf6DNm2wjNQITr3U/aFrNEmCE+BFIMs=,tag:gZn+m6x7U7TFiU2wldB18w==,type:comment]
#ENC[AES256_GCM,data:h9nTWvsuxcicgKXJCg==,iv:l2IKN5vmmiwiU3C2MS2pUkS9e9vPQZOIIJBglM8N628=,tag:dlzkKA4BgzzC0DbFHOQlXg==,type:comment]
#ENC[AES256_GCM,data:yc7IAnabgA+f8oL0r12e9m+XWAvnErfQUAB7scOD1aXG86dv5n1P5b09Qk/PabM=,iv:r1Pl/d2MzGyO76GosdpKQ5yIVozrCmQQAfHc5UO/nIM=,tag:B2pCbNzx6aMoBQSNGupBlQ==,type:comment]
#ENC[AES256_GCM,data:HDzdJViLlzSm/KeRXoAGpvDDfR97uUFsuBjp70umyr50CPnROFYKbSf3vK2+8u1l5nTI,iv:7QkZ+qN8JoP4Ylc8DgqGvt+EHYEuyEanUjmu6UQRsCM=,tag:zSxd9Y0Bbne4/25e82mYvA==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-prod
          created_at: "2024-03-27T13:27:20Z"
          enc: AQICAHgtFXPbBtEta5PfOXifxiVcy1EnqZH2ATrV2rFy7z90wgE41a8lJvK6SLy9XCiTRRBhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCK0ED1fo6pl3WiFdAgEQgDuaHRG/Zc5EG89ZpZ1vcaO+BqhV44gYxFWaxteOKw39iS+g76RSAHhFz6mH0VGkPDOiZ8SjrB91BJnC2A==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-prod
          created_at: "2024-03-27T13:27:20Z"
          enc: AQICAHgtFXPbBtEta5PfOXifxiVcy1EnqZH2ATrV2rFy7z90wgE41a8lJvK6SLy9XCiTRRBhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCK0ED1fo6pl3WiFdAgEQgDuaHRG/Zc5EG89ZpZ1vcaO+BqhV44gYxFWaxteOKw39iS+g76RSAHhFz6mH0VGkPDOiZ8SjrB91BJnC2A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-03T08:17:26Z"
    mac: ENC[AES256_GCM,data:YUtrDuDo3Lv4h+NYW53pcUHvq1q6LMZW1nXexvQnpweSWp6rDG2n3r+2Xb9j70nZqjrU84iktCi4dMN8/HPopCTzH6pkKfepOrZGoAhtXhzMil2mtB+EY+iEQkN9onNzEQpqvzsR1B5Kcq/Z+AqjNYzvzq/kzUTy2xFaxxQ5OTM=,iv:TGkqrmupk5HEsCRKP+oFNPQlXH9Q0DWff9OOOmh/9m8=,tag:kcjCFNH/ab/woaEm41I7Kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
