{{- range $key, $value := .Values.secret }}
{{- if $key }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .name }}
  name: {{ tpl .name $ }}
  {{- else }}
  name: {{ printf "%s-%s" (include "keycloak.fullname" $) ($key | replace "." "-") | trunc 63 | trimSuffix "-" }}
  {{- end }}
  {{- with .namespace }}
  namespace: {{ tpl . $ }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
stringData:
  {{ $key }}: |-
    {{- tpl (toYaml $value) $ | nindent 4 }}
{{- end -}}
