auth:
    password: ENC[AES256_GCM,data:XZ5ChEYGADVYAejr+s7qxBwbiNRbDYwyFGr1NTL3bjbusIb7uBY6ovOU4rUD/Aom9MXzJbYv7USyHdcqjcAOeA==,iv:MOvirxjjfrWwXn0oiADg/t0MgyS9d7eBIyOT2F0fJeg=,tag:3V65m13WcU6HWPkhZSlXug==,type:str]
    postgres-password: ENC[AES256_GCM,data:a76OUEqswpYeNHAJgY+oXtQjbA7kKofoBjc/+M5wUZY1uHAJebF1QK7JS6A/K294ClsA9UpMG1pV2XAHVbU9UQ==,iv:1x8zaulkhKvBYXTRDI/0Yy9lpl4Vq/zH/IdNOXqabkI=,tag:0/SEE/To2uVT0NRj/wEwsg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T12:37:02Z"
    mac: ENC[AES256_GCM,data:+CPEzP7rDU1gd8/bu2sVaEoV74uJ0QyIwM6t4YuSbXkFKt1dhBXgFgaFFOQuSAFRfdCJE7Rujtpd+nKuV7EJjVs57qshIdNwQkYtHZd4vbp6rYxGpakTQmF+ScUX6LcHabPiezL3+3Hjx9ftNEN+QDckIg7c4hiXJ0kbcO/puBc=,iv:YsddJcQuIRWLxkJzoGcWKbMRj7G/Ms9P6sdTjdyjuU0=,tag:7Gn4Pi2Ljhp8P9bv9Oqnyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
