apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoma-api.fullname" . }}
  labels:
    {{- include "yoma-api.labels" . | nindent 4 }}
stringData:
  {{ .Values.appSettings.fileName }}: |-
    {{- tpl ( toPrettyJson .Values.appSettings ) . | nindent 4 }}
