apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoma-api.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
stringData:
  {{ .Values.appSettings.fileName }}: |-
    {{- tpl ( toPrettyJson .Values.appSettings ) . | nindent 4 }}
