apiVersion: v1
kind: Service
metadata:
  name: {{ include "yoma-api.fullname" . }}
  labels:
    {{- include "yoma-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
    {{- range $k, $v := .Values.service.addPorts }}
    - name: {{ $k }}
      port: {{ $v.port }}
      targetPort: {{ $v.targetPort | default $v.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "yoma-api.selectorLabels" . | nindent 4 }}
