envSecret:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:0OejkBtLgG+NPGIwxaQXtvInbGYypuJt9Imdn3Zdjz/5,iv:bxLasSh8TJ+sCVpkazIhwdhp1UNntNiT+jzGDK+MD2o=,tag:+uw4iWRaJNe6RZpFQRVhaw==,type:str]
    KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:2Yj1TN0jOEQ=,iv:BOPeylMWtw5cKOkw3YQSa3C+BKzNRmklarFRQfJKCWI=,tag:wA6f+vrOEVuTWeyGKEKYTQ==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:zPFSryK4To9uAaA44K1pcMKOEciyszITMLFymvNV8C6esui1EnAK,iv:q6ZWbrEJMZ9db8VY9MWC3+QyL9MDmoQItatQtgAVWSg=,tag:QDImTlXRydByJfeiMts9gQ==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:VdcxVupXgzZ2N9M7Deu8aN/MpjRnAJlakt9s7yEg,iv:gmCeFFHMGozdaTOijh7T8o666ssd95HomKOrNaGPs/I=,tag:Dg7EI4k0OgDowrVSKb2s7A==,type:str]
    API_BASE_URL: ENC[AES256_GCM,data:sBonmLhP+38BY//dZzNi5REHL2+4iNsFaFMVU3ukJXqpAJ/Ucw==,iv:WVhERmxQKTvmJv5aiTwd4OcjwCDx7J/mqVZtaqVxd1E=,tag:m67aoJ1ZkEkqM4DecZQf+A==,type:str]
    KEYCLOAK_ISSUER: ENC[AES256_GCM,data:CuQZ/4cPIanUrC+w9rsjc9v+gzC+OF2IU6l0Cs75akidQIliXvlLM4tFGA==,iv:lZVBN0lkcEcUZypD1MkI5yUOQDiQrVbPaO67Gcr/bsk=,tag:Q4FT2V3P0NlOI4Ceea2z3A==,type:str]
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:jP6L4mhU+Oq+juAoMGoelD3NHSHfUWpRw1bX8Hemfiv+G1JAmHXs,iv:1OStRli4pt/CZpKOycoaMWY9HVxgRavQG+A8ePnhKaI=,tag:YeHGpWf09b8VpYg0wVP3ag==,type:str]
    NEXT_PUBLIC_GA_MEASUREMENT_ID: ENC[AES256_GCM,data:3+4RoNsURnHUptFF,iv:I0MrGR/lhFYotkJX5XfayjvDQqWTugkeuBg9ELbbAUI=,tag:nWatO0+D2XgT3IMkKGUOVw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-26T05:56:56Z"
    mac: ENC[AES256_GCM,data:vkEE2uqQY9n6jwQEGYO/H6bHUIMfUwnbnTGrHvFyLDGMG44DC8OAuJRh/PizgP3qRgfZvQ6fSI4uA9nqIwPFnh689Qzg2twGeEIRLYYoorR9O14fxUpMj0R983VfbIHbdVfbUfwIk/mBpjFV17EVQbXnWfjdyJ1+7HdLA1IGX3U=,iv:RyQZRVSqXSjn0UGqHJfdKiCMMWxnisw8Kw3BJbHfIso=,tag:mXyX/rkP2u7EwRkc7lh0GA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
