using Newtonsoft.Json;

namespace Yoma.Core.Domain.Referral.Models
{
  /// <summary>
  /// Represents a referral link created by a referrer for a specific referral program.
  /// The link acts as the parent entity for all referee engagements (claims).
  /// Whether multiple active links can exist per program for a given referrer
  /// is determined by the program configuration (MultipleLinksAllowed).
  /// The link's Id serves as the unique referral code embedded in both the full and shortened URLs.
  ///
  /// Redaction:
  /// - Not required. This model is only ever returned to:
  ///   • The referee (for their own usage),
  ///   • The referrer (for usages on their own links), or
  ///   • Admin users.
  /// No anonymous or system-wide exposure.
  /// </summary>
  public class ReferralLink
  {
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public Guid ProgramId { get; set; }

    public string ProgramName { get; set; } = null!;

    public string? ProgramDescription { get; set; }

    public int? ProgramCompletionLimitReferee { get; set; }

    public Guid UserId { get; set; }

    public string UserDisplayName { get; set; } = null!;

    public string Username { get; set; } = null!;

    public string? UserEmail { get; set; }

    public bool? UserEmailConfirmed { get; set; }

    public string? UserPhoneNumber { get; set; }

    public bool? UserPhoneNumberConfirmed { get; set; }

    public bool Blocked { get; set; }

    public DateTimeOffset? BlockedDate { get; set; }

    public Guid StatusId { get; set; }

    public ReferralLinkStatus Status { get; set; }

    public string URL { get; set; } = null!;

    public string ShortURL { get; set; } = null!;

    public string? QRCodeBase64 { get; set; }

    public int? CompletionTotal { get; set; }

    public int? CompletionBalance => ProgramCompletionLimitReferee.HasValue ? ProgramCompletionLimitReferee - (CompletionTotal ?? default) : null;

    public int? PendingTotal { get; set; }

    public int? ExpiredTotal { get; set; }

    public int? UsageTotal { get; set; }

    /// <summary>
    /// Total cumulative ZLTO reward generated by all usages of this referral link.
    /// This value represents the combined ZLTO awarded across the entire link:
    /// - ZLTO paid to the referrer for referee completions
    /// - Plus ZLTO paid to referees for their own completions
    ///
    /// Calculated per usage (rewardReferrer + rewardReferee) and incremented for every
    /// completed usage processed through the referral engine. This is a link-level total
    /// and is not role-specific.
    /// </summary>
    public decimal? ZltoRewardCumulative { get; set; }

    /// <summary>
    /// Total ZLTO awarded to the referrer across all completed usages of this link.
    /// </summary>
    public decimal ZltoRewardReferrerTotal { get; set; }

    /// <summary>
    /// Total ZLTO awarded to all referees across all completed usages of this link.
    /// </summary>
    public decimal ZltoRewardRefereeTotal { get; set; }

    public DateTimeOffset DateCreated { get; set; }

    public DateTimeOffset DateModified { get; set; }

    [JsonIgnore]
    public ReferralLinkUsageAggregate? UsageAggregate { get; set; }
  }
}
