import React from "react";
import privacyTable from "./privacy-table-data";

const PrivacySection = () => {
  return (
    <div className="flex flex-col gap-6 overflow-hidden">
      <h1
        className="font-nunito scroll-mt-24 text-xl font-bold md:text-3xl"
        id="privacy-top"
      >
        Privacy Policy
      </h1>
      <p className="text-gray-dark text-sm">Last updated: January 2026</p>

      <div className="font-nunito flex flex-col gap-2 text-sm md:text-base">
        <h2 className="text-lg font-bold text-black">Table of Contents</h2>
        <ol className="list-inside list-decimal font-semibold">
          <li>
            <a href="#privacy-1-introduction" className="hover:underline">
              Introduction
            </a>
          </li>
          <li>
            <a href="#privacy-2-principles" className="hover:underline">
              Our Privacy Principles
            </a>
          </li>
          <li>
            <a href="#privacy-3-collection" className="hover:underline">
              Information We Collect
            </a>
          </li>
          <li>
            <a href="#privacy-4-usage" className="hover:underline">
              How We Use Your Data
            </a>
          </li>
          <li>
            <a href="#privacy-5-sharing" className="hover:underline">
              Data Sharing and Partners
            </a>
          </li>
          <li>
            <a href="#privacy-6-storage" className="hover:underline">
              Data Storage and Security
            </a>
          </li>
          <li>
            <a href="#privacy-7-retention" className="hover:underline">
              Data Retention
            </a>
          </li>
          <li>
            <a href="#privacy-8-rights" className="hover:underline">
              Your Privacy Rights
            </a>
          </li>
          <li>
            <a href="#privacy-9-contact" className="hover:underline">
              Contact Us
            </a>
          </li>
        </ol>
      </div>

      <div className="flex flex-col gap-4">
        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-1-introduction"
        >
          1. Introduction
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          Yoma (Youth Agency Marketplace) is a digital platform where youth can
          develop their skills, find opportunities, and achieve impact while
          connecting to peers in a supportive community. We respect your privacy
          and are committed to protecting your personal data.
        </p>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-2-principles"
        >
          2. Our Privacy Principles
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          Our approach to privacy is guided by three key principles:
        </p>
        <ul className="text-gray-dark ml-4 list-disc text-sm md:text-base">
          <li>
            <strong>Self-Sovereign Identity (SSI):</strong> You should own and
            control your data. We aim to give you control over what you share
            and with whom.
          </li>
          <li>
            <strong>Data Portability:</strong> Your credentials and verified
            skills should be useful beyond Yoma. We use standards that allow you
            to take your achievements with you.
          </li>
          <li>
            <strong>Data Minimization:</strong> We only collect the information
            necessary to provide our services and connect you with
            opportunities.
          </li>
        </ul>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-3-collection"
        >
          3. Information We Collect
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          We collect information you provide directly to us (registration and
          profile data), information generated by your activity (opportunities,
          credentials, ZLTO), and technical information from your device.
        </p>

        <div className="items mb-3 flex flex-col justify-center">
          <table className="border-collapse border text-[.5rem] md:text-base">
            <tbody>
              <tr>
                <th className="border p-px text-left md:p-2">Section</th>
                <th className="border p-px text-left md:p-2">Data name</th>
                <th className="border p-px text-left md:p-2">Data category</th>
                <th className="border p-px text-left md:p-2">Data type</th>
                <th className="border p-px text-left md:p-2">
                  Reason for collection
                </th>
              </tr>
              {privacyTable ? (
                privacyTable.privacyTable.map((item, index) => {
                  return (
                    <tr key={index}>
                      <td className="text-gray-dark border p-px text-left md:p-2">
                        {item["Section"]}
                      </td>
                      <td className="text-gray-dark border p-px text-left md:p-2">
                        {item["Data name"]}
                      </td>
                      <td className="text-gray-dark border p-px text-left md:p-2">
                        {item["Data category"]}
                      </td>
                      <td className="text-gray-dark border p-px text-left md:p-2">
                        {item["Data type"]}
                      </td>
                      <td className="text-gray-dark border p-px text-left md:p-2">
                        {item["Reason for collection"]}
                      </td>
                    </tr>
                  );
                })
              ) : (
                <></>
              )}
            </tbody>
          </table>
        </div>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-4-usage"
        >
          4. How We Use Your Data
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          We use your information to:
        </p>
        <ul className="text-gray-dark ml-4 list-disc text-sm md:text-base">
          <li>Create and manage your account.</li>
          <li>
            Match you with relevant learning, earning, and impact opportunities.
          </li>
          <li>Issue and verify credentials (YoID) for your achievements.</li>
          <li>Facilitate the earning and redemption of ZLTO rewards.</li>
          <li>
            Improve the platform and user experience (using anonymous
            analytics).
          </li>
          <li>
            Communicate with you about your account and new opportunities.
          </li>
        </ul>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-5-sharing"
        >
          5. Data Sharing and Partners
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          We do not sell your personal data. We share data only in specific
          circumstances:
        </p>
        <ul className="text-gray-dark ml-4 list-disc text-sm md:text-base">
          <li>
            <strong>With Partners:</strong> When you choose to apply for or
            participate in a partner opportunity, we may share necessary
            information (such as your name and contact details) with that
            partner. Standard practice is that you authorize this sharing.
          </li>
          <li>
            <strong>Marketplace Vendors:</strong> When you redeem ZLTO,
            necessary transaction details are shared to fulfill the formatted
            request.
          </li>
          <li>
            <strong>Analytics Providers:</strong> We use tools like Google
            Analytics and Datadog to monitor platform performance. This data
            collection is gated by your consent preference.
          </li>
          <li>
            <strong>Legal Requirements:</strong> We may disclose information if
            required by law or to protect the safety and security of our users
            and platform.
          </li>
        </ul>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-6-storage"
        >
          6. Data Storage and Security
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          Your data is stored securely. Our primary hosting environmnent is
          Amazon Web Services (AWS) located in the Europe (Ireland) region
          (eu-west-1). We implement appropriate technical measures to protect
          your data from unauthorized access.
        </p>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-7-retention"
        >
          7. Data Retention
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          We retain your personal data only in as far as necessary to fulfill
          benefits of the platform (your lifelong skills profile) and to comply
          with legal obligations.
        </p>
        <p className="text-gray-dark text-sm md:text-base">
          Active accounts are retained indefinitely to support your learning
          journey. If an account is deleted, we aim to remove personal
          identifiers within 30 days, subject to legitimate business needs
          (e.g., fraud logs) or legal requirements.
        </p>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-8-rights"
        >
          8. Your Privacy Rights
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          Depending on your location, you have rights regarding your data,
          including:
        </p>
        <ul className="text-gray-dark ml-4 list-disc text-sm md:text-base">
          <li>Accessing your personal data.</li>
          <li>
            Correcting inaccurate data (mostly available via profile settings).
          </li>
          <li>Requesting deletion of your data.</li>
          <li>Withdrawing consent for optional processing.</li>
        </ul>
        <p className="text-gray-dark text-sm md:text-base">
          <strong>Note on Deletion:</strong> Currently, there is no automatic
          &quot;delete button&quot; in the settings. To request account
          deletion, please contact us at the email below.
        </p>

        <h2
          className="scroll-mt-24 text-base font-semibold text-black md:text-lg"
          id="privacy-9-contact"
        >
          9. Contact Us
        </h2>
        <p className="text-gray-dark text-sm md:text-base">
          If you have questions about this Privacy Policy or wish to exercise
          your rights, please contact our Data Controller:
        </p>
        <p className="text-gray-dark text-sm md:text-base">
          <strong>RLabs (Yoma)</strong>
          <br />
          Email:{" "}
          <a
            href="mailto:admin@yoma.world"
            className="text-blue-600 hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            admin@yoma.world
          </a>
          <br />
          Address: 54 Kiewiet Road, Bridgetown, Athlone 7764, Cape Town, South
          Africa
        </p>
      </div>
    </div>
  );
};

export default PrivacySection;
