// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yoma.Core.Infrastructure.JobJack.Context;

#nullable disable

namespace Yoma.Core.Infrastructure.JobJack.Migrations
{
  [DbContext(typeof(JobJackDbContext))]
  [Migration("20260803125651_JobJackDb_Initial")]
  partial class JobJackDb_Initial
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Yoma.Core.Infrastructure.JobJack.Entities.FeedSyncTracking", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid");

            b.Property<DateTimeOffset>("DateCreated")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("DateModified")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("ETag")
                      .HasColumnType("varchar(512)");

            b.Property<DateTimeOffset?>("FeedLastModified")
                      .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("FeedSyncTracking", "JobJack");
          });

      modelBuilder.Entity("Yoma.Core.Infrastructure.JobJack.Entities.Opportunity", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid");

            b.Property<string>("Category")
                      .HasColumnType("varchar(512)");

            b.Property<string>("City")
                      .HasColumnType("varchar(100)");

            b.Property<string>("Company")
                      .HasColumnType("varchar(256)");

            b.Property<string>("ContractType")
                      .HasColumnType("varchar(100)");

            b.Property<DateTimeOffset>("DateCreated")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("DateEnd")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("DateModified")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("DateStart")
                      .HasColumnType("timestamp with time zone");

            b.Property<bool?>("Deleted")
                      .HasColumnType("boolean");

            b.Property<string>("Description")
                      .HasColumnType("text");

            b.Property<string>("Duration")
                      .HasColumnType("varchar(100)");

            b.Property<DateTimeOffset?>("EmploymentStartDate")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("ExternalId")
                      .IsRequired()
                      .HasColumnType("varchar(50)");

            b.Property<string>("Location")
                      .HasColumnType("varchar(512)");

            b.Property<int?>("OpportunitiesAvailable")
                      .HasColumnType("integer");

            b.Property<string>("Province")
                      .HasColumnType("varchar(100)");

            b.Property<string>("Requirements")
                      .HasColumnType("text");

            b.Property<string>("SalaryAdditional")
                      .HasColumnType("varchar(512)");

            b.Property<string>("SalaryFrequency")
                      .HasColumnType("varchar(100)");

            b.Property<decimal?>("SalaryHigh")
                      .HasColumnType("numeric(18,2)");

            b.Property<decimal?>("SalaryLow")
                      .HasColumnType("numeric(18,2)");

            b.Property<string>("SalaryType")
                      .HasColumnType("varchar(256)");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasColumnType("varchar(512)");

            b.Property<string>("URL")
                      .HasColumnType("varchar(2048)");

            b.HasKey("Id");

            b.HasIndex("ExternalId")
                      .IsUnique();

            b.HasIndex("Deleted", "DateModified");

            b.ToTable("Opportunity", "JobJack");
          });
#pragma warning restore 612, 618
    }
  }
}
