apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoma-web.fullname" . }}
  labels:
    {{- include "yoma-web.labels" . | nindent 4 }}
stringData:
  {{- range $k,$v := .Values.envSecret }}
  {{ upper $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
