// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yoma.Core.Infrastructure.Alison.Context;

#nullable disable

namespace Yoma.Core.Infrastructure.Alison.Migrations
{
  [DbContext(typeof(AlisonDbContext))]
  [Migration("20260515044345_AlisonDb_Initial")]
  partial class AlisonDb_Initial
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.7")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Yoma.Core.Infrastructure.Alison.Entities.Opportunity", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid");

            b.Property<DateTimeOffset>("DateCreated")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("DateModified")
                      .HasColumnType("timestamp with time zone");

            b.Property<bool?>("Deleted")
                      .HasColumnType("boolean");

            b.Property<string>("ExternalId")
                      .IsRequired()
                      .HasColumnType("varchar(50)");

            b.Property<string>("PayloadHash")
                      .IsRequired()
                      .HasColumnType("varchar(128)");

            b.Property<string>("PayloadJson")
                      .IsRequired()
                      .HasColumnType("jsonb");

            b.HasKey("Id");

            b.HasIndex("ExternalId")
                      .IsUnique();

            b.HasIndex("Deleted", "DateModified");

            b.HasIndex("ExternalId", "DateCreated", "DateModified");

            b.ToTable("Opportunity", "Alison");
          });
#pragma warning restore 612, 618
    }
  }
}
