import { ProgramPathwayProgressComponent } from "./ProgramPathwayProgress";
import type { ProgramPathwayProgress } from "~/api/models/referrals";
import type { OpportunityInfo } from "~/api/models/opportunity";
import {
  PathwayOrderMode,
  PathwayCompletionRule,
} from "~/api/models/referrals";

export const PathwayPreview: React.FC = () => {
  // Mock opportunities for preview - using OpportunityInfo type
  const mockOpportunityData: Record<string, OpportunityInfo> = {
    "verify-id": {
      id: "verify-id",
      title: "Complete Identity Verification",
      description:
        "Verify your identity using Yoma's secure verification system to unlock opportunities and earn rewards.",
      type: "Task",
      organizationId: "yoma",
      organizationName: "Yoma",
      organizationLogoURL: null,
      summary: "Quick identity verification process",
      instructions: null,
      url: null,
      zltoReward: 10,
      zltoRewardCumulative: null,
      yomaReward: null,
      yomaRewardCumulative: null,
      verificationEnabled: true,
      verificationMethod: null,
      difficulty: "Easy",
      commitmentInterval: "Hour",
      commitmentIntervalCount: 1,
      commitmentIntervalDescription: "1 Hour",
      participantLimit: null,
      participantCountCompleted: 0,
      participantCountPending: 0,
      participantCountTotal: 0,
      participantLimitReached: false,
      countViewed: 0,
      countNavigatedExternalLink: 0,
      statusId: "1",
      status: "Active",
      keywords: null,
      dateStart: new Date().toISOString(),
      dateEnd: null,
      featured: false,
      engagementType: null,
      published: true,
      yomaInfoURL: "",
      isCompletable: true,
      nonCompletableReason: null,
      categories: null,
      countries: null,
      languages: null,
      skills: null,
      verificationTypes: null,
      hidden: false,
    } as OpportunityInfo,
    "digital-skills": {
      id: "digital-skills",
      title: "Digital Skills Course",
      description:
        "Learn essential digital skills including computer literacy, internet safety, and online communication.",
      type: "Learning",
      organizationId: "digital-academy",
      organizationName: "Digital Academy",
      organizationLogoURL: null,
      summary: "Master digital basics in 2 hours",
      instructions: null,
      url: null,
      zltoReward: 25,
      zltoRewardCumulative: null,
      yomaReward: null,
      yomaRewardCumulative: null,
      verificationEnabled: true,
      verificationMethod: null,
      difficulty: "Intermediate",
      commitmentInterval: "Hour",
      commitmentIntervalCount: 2,
      commitmentIntervalDescription: "2 Hours",
      participantLimit: null,
      participantCountCompleted: 0,
      participantCountPending: 0,
      participantCountTotal: 0,
      participantLimitReached: false,
      countViewed: 0,
      countNavigatedExternalLink: 0,
      statusId: "1",
      status: "Active",
      keywords: null,
      dateStart: new Date().toISOString(),
      dateEnd: null,
      featured: true,
      engagementType: null,
      published: true,
      yomaInfoURL: "",
      isCompletable: true,
      nonCompletableReason: null,
      categories: null,
      countries: null,
      languages: null,
      skills: null,
      verificationTypes: null,
      hidden: false,
    } as OpportunityInfo,
    "cv-workshop": {
      id: "cv-workshop",
      title: "CV Writing Workshop",
      description:
        "Create a professional CV that stands out. Learn formatting, content structure, and how to highlight your achievements.",
      type: "Learning",
      organizationId: "career-hub",
      organizationName: "Career Hub",
      organizationLogoURL: null,
      summary: "Build your professional CV",
      instructions: null,
      url: null,
      zltoReward: 20,
      zltoRewardCumulative: null,
      yomaReward: null,
      yomaRewardCumulative: null,
      verificationEnabled: true,
      verificationMethod: null,
      difficulty: "Easy",
      commitmentInterval: "Hour",
      commitmentIntervalCount: 1,
      commitmentIntervalDescription: "1 Hour",
      participantLimit: null,
      participantCountCompleted: 0,
      participantCountPending: 0,
      participantCountTotal: 0,
      participantLimitReached: false,
      countViewed: 0,
      countNavigatedExternalLink: 0,
      statusId: "1",
      status: "Active",
      keywords: null,
      dateStart: new Date().toISOString(),
      dateEnd: null,
      featured: false,
      engagementType: null,
      published: true,
      yomaInfoURL: "",
      isCompletable: true,
      nonCompletableReason: null,
      categories: null,
      countries: null,
      languages: null,
      skills: null,
      verificationTypes: null,
      hidden: false,
    } as OpportunityInfo,
    "community-task": {
      id: "community-task",
      title: "Community Service Project",
      description:
        "Give back to your community by participating in a local service project. Options include environmental cleanup, tutoring, or helping at community centers.",
      type: "Task",
      organizationId: "community-org",
      organizationName: "Community Connect",
      organizationLogoURL: null,
      summary: "Make a difference in your community",
      instructions: null,
      url: null,
      zltoReward: 30,
      zltoRewardCumulative: null,
      yomaReward: null,
      yomaRewardCumulative: null,
      verificationEnabled: true,
      verificationMethod: null,
      difficulty: "Intermediate",
      commitmentInterval: "Day",
      commitmentIntervalCount: 1,
      commitmentIntervalDescription: "1 Day",
      participantLimit: null,
      participantCountCompleted: 0,
      participantCountPending: 0,
      participantCountTotal: 0,
      participantLimitReached: false,
      countViewed: 0,
      countNavigatedExternalLink: 0,
      statusId: "1",
      status: "Active",
      keywords: null,
      dateStart: new Date().toISOString(),
      dateEnd: null,
      featured: true,
      engagementType: null,
      published: true,
      yomaInfoURL: "",
      isCompletable: true,
      nonCompletableReason: null,
      categories: null,
      countries: null,
      languages: null,
      skills: null,
      verificationTypes: null,
      hidden: false,
    } as OpportunityInfo,
    reflection: {
      id: "reflection",
      title: "Reflection & Feedback",
      description:
        "Share your learning journey and provide feedback on your experience. Help us improve while reflecting on your growth.",
      type: "Task",
      organizationId: "yoma",
      organizationName: "Yoma",
      organizationLogoURL: null,
      summary: "Reflect on your journey",
      instructions: null,
      url: null,
      zltoReward: 15,
      zltoRewardCumulative: null,
      yomaReward: null,
      yomaRewardCumulative: null,
      verificationEnabled: true,
      verificationMethod: null,
      difficulty: "Easy",
      commitmentInterval: "Minute",
      commitmentIntervalCount: 30,
      commitmentIntervalDescription: "30 Minutes",
      participantLimit: null,
      participantCountCompleted: 0,
      participantCountPending: 0,
      participantCountTotal: 0,
      participantLimitReached: false,
      countViewed: 0,
      countNavigatedExternalLink: 0,
      statusId: "1",
      status: "Active",
      keywords: null,
      dateStart: new Date().toISOString(),
      dateEnd: null,
      featured: false,
      engagementType: null,
      published: true,
      yomaInfoURL: "",
      isCompletable: true,
      nonCompletableReason: null,
      categories: null,
      countries: null,
      languages: null,
      skills: null,
      verificationTypes: null,
      hidden: false,
    } as OpportunityInfo,
  };

  // Mock pathway data for preview
  const mockPathway: ProgramPathwayProgress = {
    id: "preview-pathway",
    name: "Youth Onboarding Journey",
    description:
      "Complete this pathway to get verified and start earning opportunities",
    rule: PathwayCompletionRule.All,
    orderMode: PathwayOrderMode.Sequential,
    stepsCompleted: 1,
    stepsTotal: 3,
    percentComplete: 33,
    completed: false,
    isCompletable: true,
    steps: [
      {
        id: "step-1",
        name: "Get Verified",
        description: "Verify your identity to unlock opportunities",
        rule: PathwayCompletionRule.All,
        orderMode: PathwayOrderMode.Sequential,
        tasksCompleted: 1,
        tasksTotal: 1,
        percentComplete: 100,
        completed: true,
        isCompletable: true,
        tasks: [
          {
            id: "task-1",
            entityType: "Opportunity" as any,
            order: 1,
            orderDisplay: 1,
            completed: true,
            dateCompleted: new Date().toISOString(),
            opportunity: {
              id: "verify-id",
              title: "✓ Complete Identity Verification",
            },
          },
        ],
      },
      {
        id: "step-2",
        name: "Learn & Grow",
        description:
          "Complete any ONE learning opportunity to build your skills",
        rule: PathwayCompletionRule.Any,
        orderMode: PathwayOrderMode.AnyOrder,
        tasksCompleted: 0,
        tasksTotal: 2,
        percentComplete: 0,
        completed: false,
        isCompletable: true,
        tasks: [
          {
            id: "task-2",
            entityType: "Opportunity" as any,
            order: null,
            orderDisplay: 1,
            completed: false,
            dateCompleted: null,
            opportunity: {
              id: "digital-skills",
              title: "Digital Skills Course",
            },
          },
          {
            id: "task-3",
            entityType: "Opportunity" as any,
            order: null,
            orderDisplay: 2,
            completed: false,
            dateCompleted: null,
            opportunity: {
              id: "cv-workshop",
              title: "CV Writing Workshop",
            },
          },
        ],
      },
      {
        id: "step-3",
        name: "Take Action",
        description: "Apply your skills by completing these tasks in order",
        rule: PathwayCompletionRule.All,
        orderMode: PathwayOrderMode.Sequential,
        tasksCompleted: 0,
        tasksTotal: 2,
        percentComplete: 0,
        completed: false,
        isCompletable: true,
        tasks: [
          {
            id: "task-4",
            entityType: "Opportunity" as any,
            order: 1,
            orderDisplay: 1,
            completed: false,
            dateCompleted: null,
            opportunity: {
              id: "community-task",
              title: "Community Service Project",
            },
          },
          {
            id: "task-5",
            entityType: "Opportunity" as any,
            order: 2,
            orderDisplay: 2,
            completed: false,
            dateCompleted: null,
            opportunity: {
              id: "reflection",
              title: "Reflection & Feedback",
            },
          },
        ],
      },
    ],
  } as any;

  return (
    <div className="rounded-lg border border-gray-200 bg-gray-50 p-4">
      <div className="mb-3 flex items-start gap-2">
        <span className="text-2xl">👀</span>
        <div>
          <h4 className="text-sm font-bold text-gray-900">
            Example User Journey
          </h4>
          <p className="text-xs text-gray-600">
            This is what your friend might see when they use your referral link
          </p>
        </div>
      </div>
      <div className="text-sm">
        <ProgramPathwayProgressComponent
          pathway={mockPathway}
          opportunityDataMap={mockOpportunityData}
        />
      </div>
    </div>
  );
};
