service:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-subnets: ENC[AES256_GCM,data:sOXo42zIBulY5vLjr19CWJAVZO7Ji8Nq9KJusmEkpFcqEUvNddy9Atvz6o5B9G9uiC5qjjLD3pJXhIosu4piqNQ+0WhdcmocepxuyA==,iv:IGZZE7CSzIxp1Y4ug8rsyC0ILgF7aH8fUN0Q+6qIb20=,tag:fYmKJpMF95WftCWA7cZG2Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-stage
          created_at: "2023-07-27T08:58:07Z"
          enc: AQICAHjZSYvoHo/SZBZoYZnlQgvngcfu02FT/ws+tb1JKL5gAAFqKAa4zEvYHl5zfGT6jdxDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HHYcPV1nEFQcysOAgEQgDuDrtnoa3gA+tLK78KUxsZmjGhlIvziU8VwexUk4y7psFPy968rLeefc4IEZsCSip3AY8xXVkGghMMGPA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-17T09:00:57Z"
    mac: ENC[AES256_GCM,data:wv/Tn8zj3sCB9teuIO9hFUXgknDz1f8XDdR49eSjaB0huIGfQ901qfG3UNtjwjXq9QCs44Y9xVjWV3xez+Qj290qtdw2rwgzrnEP5zALBEmREJfJ9fduAPRHOeGd5UHgkb1UvQsCJxDDZfC0XKZmNPllaMNS3KFQjLRrtOPNxpY=,iv:i4vfOQOMT7OvcpltgLKZY557Y665WEAcUGoPWVJ/Hgg=,tag:47vKGCFf6S5VJ8k6fMuBAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
