image:
  repository: ghcr.io/didx-xyz/yoma-web
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

env:
  NEXT_PUBLIC_API_BASE_URL: https://api.yoma.world/api/v3
  NEXT_PUBLIC_ENVIRONMENT: production
  MARKETPLACE_ENABLED: true

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        if ($host = 'app.yoma.africa') {
          rewrite ^ https://app.yoma.world$request_uri permanent;
        }
        if ($host = 'partner.yoma.world') {
          rewrite ^ https://app.yoma.world$request_uri permanent;
        }
        if ($request_uri = '/register') {
          rewrite ^ https://app.yoma.world permanent;
        }
        if ($request_uri = '/login') {
          rewrite ^ https://app.yoma.world permanent;
        }
        if ($request_uri = '/employer/auth/login') {
          rewrite ^ https://app.yoma.world permanent;
        }
    rules:
      - host: app.yoma.world
      - host: partner.yoma.world
      - host: app.yoma.africa
  external:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        if ($host = 'app.yoma.africa') {
          rewrite ^ https://app.yoma.world$request_uri permanent;
        }
        if ($host = 'partner.yoma.world') {
          rewrite ^ https://app.yoma.world$request_uri permanent;
        }
        if ($host = 'www.yoma.world') {
          rewrite ^ https://app.yoma.world$request_uri permanent;
        }
        if ($request_uri = '/register') {
          rewrite ^ https://app.yoma.world permanent;
        }
        if ($request_uri = '/login') {
          rewrite ^ https://app.yoma.world permanent;
        }
        if ($request_uri = '/employer/auth/login') {
          rewrite ^ https://app.yoma.world permanent;
        }
    rules:
      - host: app.yoma.world
      - host: partner.yoma.world
      - host: app.yoma.africa
      - host: www.yoma.world
