service:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-subnets: ENC[AES256_GCM,data:SYn7T2F0cWPSLGElUnM8EmApB+vcZPFemt3gqtNvr3hW3GuvtcW1aB6AYoLGNjy0Mklcpma7SgLWv8R5SpXwZDzUOdWN0QQojR82WQ==,iv:XHHfGxUMq2/A+7/0dJ7NZyNn2Jdx+jsRAosyrr3V1TA=,tag:j+Z4rnGxul/vICwJ3jhINg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: yoma-sso-dev
        - arn: arn:aws:kms:eu-west-1:210913241065:alias/helm/yoma-dev
          created_at: "2023-09-18T12:43:26Z"
          enc: AQICAHiIBZY/vSCV0N0rJ1zU5SgMLl7KVz/655pZ90kE4uwaNwGDC3EwSg6skDuyETp/AVVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM59JE9ckC6/q58ZA9AgEQgDsvEM10JhPmz9S7yeMijYwZuqUVQjE1x+GWhw2qBf3I0jA3nxPHB0sutIOIm67Fd3uROQ+Jfy/CNPCdRQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-13T11:49:56Z"
    mac: ENC[AES256_GCM,data:x+nLq5jXBh5eZWjSIL7bV1UaFDis4VVVDSxY6OhXxF5VxbKxAGPoPbA8b2ioIlScq1U61NVZF0KqsxYO/vMdPmLHjccy5ZuVanAAVNumFybTQ0kTYV8FymUcL+LdigpWkK7bT4dUE2hBXswIC+tGdnpI9gQGei/NYdeBpZVFzc4=,iv:Y6K5ZsL5vPd97ptmUULsoj2ayQCBdjPCEPiI2bpo9g4=,tag:Kmekvm5jk2i+/xHlBrho1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
