// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yoma.Core.Infrastructure.Jobberman.Context;

#nullable disable

namespace Yoma.Core.Infrastructure.Jobberman.Migrations
{
    [DbContext(typeof(JobbermanDbContext))]
    [Migration("20260429091851_JobbermanDb_Initial")]
    partial class JobbermanDb_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yoma.Core.Infrastructure.Jobberman.Entities.FeedSyncTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCodeAlpha2")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset?>("FeedLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCodeAlpha2")
                        .IsUnique();

                    b.ToTable("FeedSyncTracking", "Jobberman");
                });

            modelBuilder.Entity("Yoma.Core.Infrastructure.Jobberman.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("CountryCodeAlpha2")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("URL")
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("WorkType")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("CountryCodeAlpha2", "SourceId")
                        .IsUnique();

                    b.HasIndex("ExternalId", "DateCreated", "DateModified");

                    b.ToTable("Opportunity", "Jobberman");
                });
#pragma warning restore 612, 618
        }
    }
}
