keycloak:
    secrets:
        webhook:
            stringData:
                WEBHOOK_HTTP_AUTH_USERNAME: ENC[AES256_GCM,data:BRHMIV/P3Q==,iv:/IgZPIHS/7AByGy8pSpXgEyUpNmnWjFSl26ftgLppBA=,tag:NHPy23TXOrlYUxac+MO8GQ==,type:str]
                WEBHOOK_HTTP_AUTH_PASSWORD: ENC[AES256_GCM,data:9zsU1ymE4DeUOnVaUxW2KzvtU3fF4vtYHF4LPZF7mgE=,iv:KHLpurZVBcMfjFgnX4nhI200Lw8Wbdl8cPyJh3ADx8Y=,tag:4bS6K7WiZ1A8nODD3D5qmA==,type:str]
                #ENC[AES256_GCM,data:+gwjVZco/A==,iv:Q/7uYC3nOKBjijLuDWYM1hVLbuKkg4BlOwybQGjqP0U=,tag:Y4vovcj0VSL+Ix26fYIH3Q==,type:comment]
                #ENC[AES256_GCM,data:lltrqHjMjrp+ZaGwOXM=,iv:kTnOAn3acFbMjFUE1nZNigomN3LrtOx0U2n1SFwlBeg=,tag:YdbwJyOLZV7ws5JDvhzJWg==,type:comment]
                #ENC[AES256_GCM,data:VvwA2+9/yCyjQNc1JFM96yUxJr/orj07vnGjUY/hL3JB7saF7H6GSpBI,iv:4Xxc8MPEVT8SdFQSpfBBxPPoCCRGGQTdb8nw65+xnJ8=,tag:gLS1vBprSHHkTpkow6PjZA==,type:comment]
                #ENC[AES256_GCM,data:o8X/VsS2vcLN6OoG5Q02lJNjTL6GSBgVq5W8/znbImHez42a0IqPpLBnPna+Dq6Ij9LTzAF3mYYfsnXbLfKcRpxj,iv:PXb3RXOC3/9JfqoNqUTyukReRhu6cE7glEojY/cH6B4=,tag:QvPLh2JFJ7515FbUuzL6Wg==,type:comment]
    twilio:
        stringData:
            sid: ENC[AES256_GCM,data:N0M1bMHJtRS3CcHOiOB1MMFbk7bZHdM4HE4imYCXxHe1MQ==,iv:J3sMhIu1gxQClMakplqMTYxlTzH4a5KtMWdK4WqLdHs=,tag:GkDbZAs4enbs2MVzZDFy4g==,type:str]
            token: ENC[AES256_GCM,data:IbnlvLumyhD3x+H5LU5sxBdLDllqtfa6+rDZpvUywYo=,iv:0TNBXYs3DeyuSbgI4R11Ak9ciWJd2Q8TEIxXrcQy0YE=,tag:RyX16zac9qL6uhTZt94R3w==,type:str]
            #ENC[AES256_GCM,data:/r0Q15phJVHt6oQMz8fGHjD5TQ9INRGqbfOjN36gIA==,iv:uOm8dT4fNji69McgpBDfWHSt3FhfiJvPlv2dwgBsR3c=,tag:pkBMc1TVfDBGil/fsOv0Vg==,type:comment]
            number: ENC[AES256_GCM,data:KDiVNPKYL5cqOns=,iv:cQiCo1p6KpU5TzBUu0kvyVrHtgNdCSIC75MXGJBtSJA=,tag:ddh3y+nvlbHnMW7TjPlk8A==,type:str]
config-cli:
    secrets:
        KEYCLOAK_USER: ENC[AES256_GCM,data:k/b9R1DS3lw=,iv:n4OGjLPXpPoyrxCtCz+BPmwwy+fDcD6aG1J1whUzuXw=,tag:Pd+vak3/ZukMe3fcRqHFpg==,type:str]
        SMTP_PASSWORD: ENC[AES256_GCM,data:LwCR9PF2z73J1zlZFlFa8ixC0kUNXaUZknnD8HkAlJvh9Cdf2d+VpgVpBVrZFNduhXpP0KdhCLVKLuJCRaVjxfBHpXQR,iv:CMpgocrcM6xEBdQYOLBrCk5IrbVqXYEvV1C69nY44do=,tag:qvoX9ySxBsp6vUMkzDeVHA==,type:str]
        SA_YOMA_API_PASSWORD: ENC[AES256_GCM,data:MPLCY1E3Swj039pGRR3rVk+kd/yTu8wpMoE/am23nTWGkrO1ESLQOhYSjvhQpR75mBGgAjTdUydLGLIXDN3l2A==,iv:c0tlFfzlwfOJbEU7jkdMZlAv73zi4HmPxwRl25Od7Y0=,tag:SJVUKxl48OhTlDfi9DBb5Q==,type:str]
        CLIENT_GOODWALL_URL: ENC[AES256_GCM,data:kRsz3mgknW0zzsnZ59eTZYvfmmYXWwo=,iv:QeP1oAHahIeMXqlC5LdD/iLaPXLsbwaWSc9FS1phmzk=,tag:kzPMSf7CzMDQCko8psBMuw==,type:str]
        CLIENT_GOODWALL_URL_REDIRECT: ENC[AES256_GCM,data:R/pdSyxVNXc9RyWtjoLZpXV6TR/0XYExBQ1I,iv:rWePtIjV2kVk5mR5tkEzotV0glvpOa5Nbdb+fxqnyY4=,tag:QOAz2ABW0d2C58bxnFpcNA==,type:str]
        CLIENT_YOMA_API_SECRET: ENC[AES256_GCM,data:/13ejRP70GT8dhcdpU3NV3FUMz5nKpQr2W30P3zJuTqaiOUF6UW9gODdJ6JLaX7lEWv3ZqboeKucc3/jwUBYZA==,iv:LvsxCVvjI11AsoqMychwZK+7/Dxm49CzHmiJod+a3/U=,tag:MEO/qO2uK5ooHzWRQOktQg==,type:str]
        CLIENT_ATINGI_SECRET: ENC[AES256_GCM,data:vE6SmopFwiyZLum5ieuggToFL42QNKFpCUDm1TWRGdCY6tp9o+bosUl7NXgvyZQZaAkDnARnK5p88yVopHxd0A==,iv:bv4PD4UnUwWk0IKfbuwX9v8ckfYHFDR09KplS0T4xwg=,tag:1paHr+pvPGSRAZe5kT4gyw==,type:str]
        CLIENT_GOODWALL_SECRET: ENC[AES256_GCM,data:C73yEEKzkVGmVcolcqqmmERQBm1z8HImt4/s3DsIRuYatvkhgSR3zwiLsvB583UbziyBPBdzT9BZ5WPrAVQfEQ==,iv:bNwjc70HtWSh7Dw7Fw7MkD0H/YfFeq3LqBejEiakKXc=,tag:HoZym31S/7EY8JGygHGN4w==,type:str]
        CLIENT_YOMA_WEB_SECRET: ENC[AES256_GCM,data:3r2qJjYy5glkPvZd8A0wq75Kij50XuFH9IufA7DcNvmfx4klDHEawN+l+q/irrQr/OMsexKCgV0xg6UuwV2x6w==,iv:kuymcYMqtc6hx8/Rv+4gYN00GccXWVcr/bbSkbKU2GE=,tag:6WM/PMi/7WVmEV8bRTRvxg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-prod
          created_at: "2024-03-27T13:21:02Z"
          enc: AQICAHgtFXPbBtEta5PfOXifxiVcy1EnqZH2ATrV2rFy7z90wgEVlL7BoqTZbw17bbd8LtDXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbBvTjVUSQAlicXR9AgEQgDuuwIVxpxb/4XiePVnQArTyqvTYyGzkx6BZEYl8Ekp2bq5DOQ7tAzJsdpRmdc1IsRizEIR/Po3jEJ22DA==
          aws_profile: yoma-sso-prod
        - arn: arn:aws:kms:eu-west-1:645438834644:alias/helm/yoma-prod
          created_at: "2024-03-27T13:21:02Z"
          enc: AQICAHgtFXPbBtEta5PfOXifxiVcy1EnqZH2ATrV2rFy7z90wgEVlL7BoqTZbw17bbd8LtDXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbBvTjVUSQAlicXR9AgEQgDuuwIVxpxb/4XiePVnQArTyqvTYyGzkx6BZEYl8Ekp2bq5DOQ7tAzJsdpRmdc1IsRizEIR/Po3jEJ22DA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-14T10:14:37Z"
    mac: ENC[AES256_GCM,data:1lVuCQAomxtW+E8zSutRekucH9sAUJ1Fs+yTZya3xVlcPMCXPb3g5jQgMa9ajagGAriPs63x2EKjALrLZWCnyyQBtn48NJHO5pJkquq05tiqeCCVuArs9ZGMWDzewZkIqghWyj55+gkZbP/tdXjFK0hSYgIKm0T3J14gdPqxsds=,iv:Dnf9fXLpc6+KH0xyOne+o/ePJ+t7pWSVSt0wihKO+8o=,tag:K1Rzkl8YEJckbbwe5soG5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
