ingress:
  internal:
    enabled: true
    rules:
      - host: "{{ .Values.keycloak.ingressDomain }}"
        paths:
          - path: /auth
  internal-admin:
    enabled: true
    rules:
      - host: auth.{{ .Values.keycloak.ingressDomain }}
  external:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        # Vercel passes the incorrect 'host' value in the 'Forwarded' header
        # The 'X-Forwarded-Host' is already correct from Vercel
        # We just need to fix the 'Forwarded' header to use it

        # Build new 'Forwarded' header using the correct host from 'X-Forwarded-Host'
        set $correct_forwarded "for=$remote_addr;host=$http_x_forwarded_host;proto=$scheme";

        # If 'X-Real-IP' exists (from Vercel), use that for the 'for' field
        if ($http_x_real_ip) {
          set $correct_forwarded "for=$http_x_real_ip;host=$http_x_forwarded_host;proto=$scheme";
        }

        # Override the 'Forwarded' header with the corrected version
        proxy_set_header Forwarded $correct_forwarded;
    rules:
      - host: "{{ .Values.keycloak.ingressDomain }}"
        paths:
          - path: /auth/realms/yoma
          - path: /auth/resources
          - path: /auth/js
      # Required for Vercel Rewrite
      - host: keycloak.{{ .Values.keycloak.ingressDomain }}
        paths:
          - path: /auth/realms/yoma
          - path: /auth/resources
          - path: /auth/js

postInstallHook:
  enabled: false

keycloak:
  replicas: 2

  ingressDomain: yoma.world

  resources:
    requests:
      cpu: 250m
      memory: 2048Mi
    limits:
      cpu: 4000m
      memory: 2048Mi

  themes:
    enabled: true
    ref: master

  extraEnvFrom: |-
    - secretRef:
        name: keycloak-webhook

  database:
    existingSecret: keycloak-db
    existingSecretKey: password
    vendor: postgres

  affinity: |-
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node.kubernetes.io/lifecycle
                operator: In
                values:
                  - spot
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 12 }}
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: NotIn
                values:
                  - test
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 12 }}
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: NotIn
                values:
                  - test
          topologyKey: topology.kubernetes.io/zone

config-cli:
  enabled: true
  env:
    KEYCLOAK_URL: https://yoma.world/auth
    IMPORT_FILES_LOCATIONS: "/init/*.yaml"
    # KEYCLOAK_USER: xxx
    # REALM_YOMA_ADMIN_CLI_SECRET: xxx
    # SMTP_PASSWORD: SG.xxx
    CLIENT_YOMA_API_URL: https://api.yoma.world
    CLIENT_YOMA_WEB_URL: https://yoma.world
    CLIENT_ATINGI_URL: https://online.atingi.org
    CLIENT_ATINGI_URL_REDIRECT: https://keycloak.atingi.org/realms/master/broker/yoma-prod/endpoint
    CLIENT_ATINGI_URL_POST_LOGOUT_REDIRECT: https://keycloak.atingi.org/realms/master/broker/yoma-prod/endpoint
    CLIENT_GOODWALL_URL: https://www.goodwall.io
    CLIENT_GOODWALL_URL_REDIRECT: goodwallauth://yomaredirect
    CLIENT_IIASA_URL: https://geoqauth.main.geo-wiki.org
    CLIENT_IIASA_URL_REDIRECT: https://geoqauth.main.geo-wiki.org/signin-yoma-oidc
    CLIENT_UNICEF_KENYA_ENABLED: "false"
    CLIENT_MINI_SASS_URL: https://minisass.org
    CLIENT_MINI_SASS_URL_REDIRECT: https://minisass.org/authentication/api/yoma/callback
    GOOGLE_CLIENT_ID: 1088325631106-l5e6h1lgu0irqqjvb8fko8d7viru716f.apps.googleusercontent.com
    FACEBOOK_CLIENT_ID: "1095100448743505"

  init:
    enabled: true
    ref: master

  existingSecret: keycloak-admin
  existingSecretKey: password

  extraVolumes: |-
    - name: init
      emptyDir: {}

  extraVolumeMounts: |-
    - name: init
      mountPath: /init

  initContainers: |-
    {{- if .Values.init.enabled }}
    - name: download-realm
      image: docker.io/busybox:stable
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |-
          cd /init
          wget -O - \
            --header="Accept:application/vnd.github.v3.raw" \
            https://api.github.com/repos/didx-xyz/yoma/tarball/{{ .Values.init.ref }} | tar xz
          cp -v ./didx-xyz-yoma-*/src/keycloak/exports/* /init/
          rm -rf ./didx-xyz-yoma-*
      volumeMounts:
        - name: init
          mountPath: /init
    {{- end }}
